//! Rust port of the `statenum_t` enumeration from `vendor/doomgeneric/info.h`.
//!
//! `statenum_t` indexes the global `states[]` table in `info.c` and is used
//! throughout the game logic to walk thinker state machines (weapons, mobjs,
//! sectors, etc.). In the C source it is an enum; here it is exposed as a flat
//! list of `pub const c_int` values so any module that takes a state index by
//! integer (e.g. `P_SetMobjState`, `P_SetPsprite`) can be called with the
//! original symbolic constant unchanged.
//!
//! The values match the C enum order one-for-one. Names follow the C
//! `S_<UPPER>` convention. Variants like `S_PUNCH1..S_PUNCH5` are individual
//! animation frames of the parent state (`S_PUNCH`); `*DOWN`/`*UP` are the
//! weapon raise/lower frames; `*FLASH*` are the muzzle-flash overlays.

#![allow(non_upper_case_globals)]

use std::ffi::c_int;

/// Sentinel "no state" id (state 0).
pub const S_NULL: c_int = 0;
/// Terminal state used when a sector light effect finishes.
pub const S_LIGHTDONE: c_int = 1;
/// `S_PUNCH` thinker state (index 2).
pub const S_PUNCH: c_int = 2;
/// `S_PUNCHDOWN` thinker state (index 3).
pub const S_PUNCHDOWN: c_int = 3;
/// `S_PUNCHUP` thinker state (index 4).
pub const S_PUNCHUP: c_int = 4;
/// `S_PUNCH1` thinker state (index 5).
pub const S_PUNCH1: c_int = 5;
/// `S_PUNCH2` thinker state (index 6).
pub const S_PUNCH2: c_int = 6;
/// `S_PUNCH3` thinker state (index 7).
pub const S_PUNCH3: c_int = 7;
/// `S_PUNCH4` thinker state (index 8).
pub const S_PUNCH4: c_int = 8;
/// `S_PUNCH5` thinker state (index 9).
pub const S_PUNCH5: c_int = 9;
/// `S_PISTOL` thinker state (index 10).
pub const S_PISTOL: c_int = 10;
/// `S_PISTOLDOWN` thinker state (index 11).
pub const S_PISTOLDOWN: c_int = 11;
/// `S_PISTOLUP` thinker state (index 12).
pub const S_PISTOLUP: c_int = 12;
/// `S_PISTOL1` thinker state (index 13).
pub const S_PISTOL1: c_int = 13;
/// `S_PISTOL2` thinker state (index 14).
pub const S_PISTOL2: c_int = 14;
/// `S_PISTOL3` thinker state (index 15).
pub const S_PISTOL3: c_int = 15;
/// `S_PISTOL4` thinker state (index 16).
pub const S_PISTOL4: c_int = 16;
/// `S_PISTOLFLASH` thinker state (index 17).
pub const S_PISTOLFLASH: c_int = 17;
/// `S_SGUN` thinker state (index 18).
pub const S_SGUN: c_int = 18;
/// `S_SGUNDOWN` thinker state (index 19).
pub const S_SGUNDOWN: c_int = 19;
/// `S_SGUNUP` thinker state (index 20).
pub const S_SGUNUP: c_int = 20;
/// `S_SGUN1` thinker state (index 21).
pub const S_SGUN1: c_int = 21;
/// `S_SGUN2` thinker state (index 22).
pub const S_SGUN2: c_int = 22;
/// `S_SGUN3` thinker state (index 23).
pub const S_SGUN3: c_int = 23;
/// `S_SGUN4` thinker state (index 24).
pub const S_SGUN4: c_int = 24;
/// `S_SGUN5` thinker state (index 25).
pub const S_SGUN5: c_int = 25;
/// `S_SGUN6` thinker state (index 26).
pub const S_SGUN6: c_int = 26;
/// `S_SGUN7` thinker state (index 27).
pub const S_SGUN7: c_int = 27;
/// `S_SGUN8` thinker state (index 28).
pub const S_SGUN8: c_int = 28;
/// `S_SGUN9` thinker state (index 29).
pub const S_SGUN9: c_int = 29;
/// `S_SGUNFLASH1` thinker state (index 30).
pub const S_SGUNFLASH1: c_int = 30;
/// `S_SGUNFLASH2` thinker state (index 31).
pub const S_SGUNFLASH2: c_int = 31;
/// `S_DSGUN` thinker state (index 32).
pub const S_DSGUN: c_int = 32;
/// `S_DSGUNDOWN` thinker state (index 33).
pub const S_DSGUNDOWN: c_int = 33;
/// `S_DSGUNUP` thinker state (index 34).
pub const S_DSGUNUP: c_int = 34;
/// `S_DSGUN1` thinker state (index 35).
pub const S_DSGUN1: c_int = 35;
/// `S_DSGUN2` thinker state (index 36).
pub const S_DSGUN2: c_int = 36;
/// `S_DSGUN3` thinker state (index 37).
pub const S_DSGUN3: c_int = 37;
/// `S_DSGUN4` thinker state (index 38).
pub const S_DSGUN4: c_int = 38;
/// `S_DSGUN5` thinker state (index 39).
pub const S_DSGUN5: c_int = 39;
/// `S_DSGUN6` thinker state (index 40).
pub const S_DSGUN6: c_int = 40;
/// `S_DSGUN7` thinker state (index 41).
pub const S_DSGUN7: c_int = 41;
/// `S_DSGUN8` thinker state (index 42).
pub const S_DSGUN8: c_int = 42;
/// `S_DSGUN9` thinker state (index 43).
pub const S_DSGUN9: c_int = 43;
/// `S_DSGUN10` thinker state (index 44).
pub const S_DSGUN10: c_int = 44;
/// `S_DSNR1` thinker state (index 45).
pub const S_DSNR1: c_int = 45;
/// `S_DSNR2` thinker state (index 46).
pub const S_DSNR2: c_int = 46;
/// `S_DSGUNFLASH1` thinker state (index 47).
pub const S_DSGUNFLASH1: c_int = 47;
/// `S_DSGUNFLASH2` thinker state (index 48).
pub const S_DSGUNFLASH2: c_int = 48;
/// `S_CHAIN` thinker state (index 49).
pub const S_CHAIN: c_int = 49;
/// `S_CHAINDOWN` thinker state (index 50).
pub const S_CHAINDOWN: c_int = 50;
/// `S_CHAINUP` thinker state (index 51).
pub const S_CHAINUP: c_int = 51;
/// `S_CHAIN1` thinker state (index 52).
pub const S_CHAIN1: c_int = 52;
/// `S_CHAIN2` thinker state (index 53).
pub const S_CHAIN2: c_int = 53;
/// `S_CHAIN3` thinker state (index 54).
pub const S_CHAIN3: c_int = 54;
/// `S_CHAINFLASH1` thinker state (index 55).
pub const S_CHAINFLASH1: c_int = 55;
/// `S_CHAINFLASH2` thinker state (index 56).
pub const S_CHAINFLASH2: c_int = 56;
/// `S_MISSILE` thinker state (index 57).
pub const S_MISSILE: c_int = 57;
/// `S_MISSILEDOWN` thinker state (index 58).
pub const S_MISSILEDOWN: c_int = 58;
/// `S_MISSILEUP` thinker state (index 59).
pub const S_MISSILEUP: c_int = 59;
/// `S_MISSILE1` thinker state (index 60).
pub const S_MISSILE1: c_int = 60;
/// `S_MISSILE2` thinker state (index 61).
pub const S_MISSILE2: c_int = 61;
/// `S_MISSILE3` thinker state (index 62).
pub const S_MISSILE3: c_int = 62;
/// `S_MISSILEFLASH1` thinker state (index 63).
pub const S_MISSILEFLASH1: c_int = 63;
/// `S_MISSILEFLASH2` thinker state (index 64).
pub const S_MISSILEFLASH2: c_int = 64;
/// `S_MISSILEFLASH3` thinker state (index 65).
pub const S_MISSILEFLASH3: c_int = 65;
/// `S_MISSILEFLASH4` thinker state (index 66).
pub const S_MISSILEFLASH4: c_int = 66;
/// `S_SAW` thinker state (index 67).
pub const S_SAW: c_int = 67;
/// `S_SAWB` thinker state (index 68).
pub const S_SAWB: c_int = 68;
/// `S_SAWDOWN` thinker state (index 69).
pub const S_SAWDOWN: c_int = 69;
/// `S_SAWUP` thinker state (index 70).
pub const S_SAWUP: c_int = 70;
/// `S_SAW1` thinker state (index 71).
pub const S_SAW1: c_int = 71;
/// `S_SAW2` thinker state (index 72).
pub const S_SAW2: c_int = 72;
/// `S_SAW3` thinker state (index 73).
pub const S_SAW3: c_int = 73;
/// `S_PLASMA` thinker state (index 74).
pub const S_PLASMA: c_int = 74;
/// `S_PLASMADOWN` thinker state (index 75).
pub const S_PLASMADOWN: c_int = 75;
/// `S_PLASMAUP` thinker state (index 76).
pub const S_PLASMAUP: c_int = 76;
/// `S_PLASMA1` thinker state (index 77).
pub const S_PLASMA1: c_int = 77;
/// `S_PLASMA2` thinker state (index 78).
pub const S_PLASMA2: c_int = 78;
/// `S_PLASMAFLASH1` thinker state (index 79).
pub const S_PLASMAFLASH1: c_int = 79;
/// `S_PLASMAFLASH2` thinker state (index 80).
pub const S_PLASMAFLASH2: c_int = 80;
/// `S_BFG` thinker state (index 81).
pub const S_BFG: c_int = 81;
/// `S_BFGDOWN` thinker state (index 82).
pub const S_BFGDOWN: c_int = 82;
/// `S_BFGUP` thinker state (index 83).
pub const S_BFGUP: c_int = 83;
/// `S_BFG1` thinker state (index 84).
pub const S_BFG1: c_int = 84;
/// `S_BFG2` thinker state (index 85).
pub const S_BFG2: c_int = 85;
/// `S_BFG3` thinker state (index 86).
pub const S_BFG3: c_int = 86;
/// `S_BFG4` thinker state (index 87).
pub const S_BFG4: c_int = 87;
/// `S_BFGFLASH1` thinker state (index 88).
pub const S_BFGFLASH1: c_int = 88;
/// `S_BFGFLASH2` thinker state (index 89).
pub const S_BFGFLASH2: c_int = 89;
/// `S_BLOOD1` thinker state (index 90).
pub const S_BLOOD1: c_int = 90;
/// `S_BLOOD2` thinker state (index 91).
pub const S_BLOOD2: c_int = 91;
/// `S_BLOOD3` thinker state (index 92).
pub const S_BLOOD3: c_int = 92;
/// `S_PUFF1` thinker state (index 93).
pub const S_PUFF1: c_int = 93;
/// `S_PUFF2` thinker state (index 94).
pub const S_PUFF2: c_int = 94;
/// `S_PUFF3` thinker state (index 95).
pub const S_PUFF3: c_int = 95;
/// `S_PUFF4` thinker state (index 96).
pub const S_PUFF4: c_int = 96;
/// `S_TBALL1` thinker state (index 97).
pub const S_TBALL1: c_int = 97;
/// `S_TBALL2` thinker state (index 98).
pub const S_TBALL2: c_int = 98;
/// `S_TBALLX1` thinker state (index 99).
pub const S_TBALLX1: c_int = 99;
/// `S_TBALLX2` thinker state (index 100).
pub const S_TBALLX2: c_int = 100;
/// `S_TBALLX3` thinker state (index 101).
pub const S_TBALLX3: c_int = 101;
/// `S_RBALL1` thinker state (index 102).
pub const S_RBALL1: c_int = 102;
/// `S_RBALL2` thinker state (index 103).
pub const S_RBALL2: c_int = 103;
/// `S_RBALLX1` thinker state (index 104).
pub const S_RBALLX1: c_int = 104;
/// `S_RBALLX2` thinker state (index 105).
pub const S_RBALLX2: c_int = 105;
/// `S_RBALLX3` thinker state (index 106).
pub const S_RBALLX3: c_int = 106;
/// `S_PLASBALL` thinker state (index 107).
pub const S_PLASBALL: c_int = 107;
/// `S_PLASBALL2` thinker state (index 108).
pub const S_PLASBALL2: c_int = 108;
/// `S_PLASEXP` thinker state (index 109).
pub const S_PLASEXP: c_int = 109;
/// `S_PLASEXP2` thinker state (index 110).
pub const S_PLASEXP2: c_int = 110;
/// `S_PLASEXP3` thinker state (index 111).
pub const S_PLASEXP3: c_int = 111;
/// `S_PLASEXP4` thinker state (index 112).
pub const S_PLASEXP4: c_int = 112;
/// `S_PLASEXP5` thinker state (index 113).
pub const S_PLASEXP5: c_int = 113;
/// `S_ROCKET` thinker state (index 114).
pub const S_ROCKET: c_int = 114;
/// `S_BFGSHOT` thinker state (index 115).
pub const S_BFGSHOT: c_int = 115;
/// `S_BFGSHOT2` thinker state (index 116).
pub const S_BFGSHOT2: c_int = 116;
/// `S_BFGLAND` thinker state (index 117).
pub const S_BFGLAND: c_int = 117;
/// `S_BFGLAND2` thinker state (index 118).
pub const S_BFGLAND2: c_int = 118;
/// `S_BFGLAND3` thinker state (index 119).
pub const S_BFGLAND3: c_int = 119;
/// `S_BFGLAND4` thinker state (index 120).
pub const S_BFGLAND4: c_int = 120;
/// `S_BFGLAND5` thinker state (index 121).
pub const S_BFGLAND5: c_int = 121;
/// `S_BFGLAND6` thinker state (index 122).
pub const S_BFGLAND6: c_int = 122;
/// `S_BFGEXP` thinker state (index 123).
pub const S_BFGEXP: c_int = 123;
/// `S_BFGEXP2` thinker state (index 124).
pub const S_BFGEXP2: c_int = 124;
/// `S_BFGEXP3` thinker state (index 125).
pub const S_BFGEXP3: c_int = 125;
/// `S_BFGEXP4` thinker state (index 126).
pub const S_BFGEXP4: c_int = 126;
/// `S_EXPLODE1` thinker state (index 127).
pub const S_EXPLODE1: c_int = 127;
/// `S_EXPLODE2` thinker state (index 128).
pub const S_EXPLODE2: c_int = 128;
/// `S_EXPLODE3` thinker state (index 129).
pub const S_EXPLODE3: c_int = 129;
/// `S_TFOG` thinker state (index 130).
pub const S_TFOG: c_int = 130;
/// `S_TFOG01` thinker state (index 131).
pub const S_TFOG01: c_int = 131;
/// `S_TFOG02` thinker state (index 132).
pub const S_TFOG02: c_int = 132;
/// `S_TFOG2` thinker state (index 133).
pub const S_TFOG2: c_int = 133;
/// `S_TFOG3` thinker state (index 134).
pub const S_TFOG3: c_int = 134;
/// `S_TFOG4` thinker state (index 135).
pub const S_TFOG4: c_int = 135;
/// `S_TFOG5` thinker state (index 136).
pub const S_TFOG5: c_int = 136;
/// `S_TFOG6` thinker state (index 137).
pub const S_TFOG6: c_int = 137;
/// `S_TFOG7` thinker state (index 138).
pub const S_TFOG7: c_int = 138;
/// `S_TFOG8` thinker state (index 139).
pub const S_TFOG8: c_int = 139;
/// `S_TFOG9` thinker state (index 140).
pub const S_TFOG9: c_int = 140;
/// `S_TFOG10` thinker state (index 141).
pub const S_TFOG10: c_int = 141;
/// `S_IFOG` thinker state (index 142).
pub const S_IFOG: c_int = 142;
/// `S_IFOG01` thinker state (index 143).
pub const S_IFOG01: c_int = 143;
/// `S_IFOG02` thinker state (index 144).
pub const S_IFOG02: c_int = 144;
/// `S_IFOG2` thinker state (index 145).
pub const S_IFOG2: c_int = 145;
/// `S_IFOG3` thinker state (index 146).
pub const S_IFOG3: c_int = 146;
/// `S_IFOG4` thinker state (index 147).
pub const S_IFOG4: c_int = 147;
/// `S_IFOG5` thinker state (index 148).
pub const S_IFOG5: c_int = 148;
/// `S_PLAY` thinker state (index 149).
pub const S_PLAY: c_int = 149;
/// `S_PLAY_RUN1` thinker state (index 150).
pub const S_PLAY_RUN1: c_int = 150;
/// `S_PLAY_RUN2` thinker state (index 151).
pub const S_PLAY_RUN2: c_int = 151;
/// `S_PLAY_RUN3` thinker state (index 152).
pub const S_PLAY_RUN3: c_int = 152;
/// `S_PLAY_RUN4` thinker state (index 153).
pub const S_PLAY_RUN4: c_int = 153;
/// `S_PLAY_ATK1` thinker state (index 154).
pub const S_PLAY_ATK1: c_int = 154;
/// `S_PLAY_ATK2` thinker state (index 155).
pub const S_PLAY_ATK2: c_int = 155;
/// `S_PLAY_PAIN` thinker state (index 156).
pub const S_PLAY_PAIN: c_int = 156;
/// `S_PLAY_PAIN2` thinker state (index 157).
pub const S_PLAY_PAIN2: c_int = 157;
/// `S_PLAY_DIE1` thinker state (index 158).
pub const S_PLAY_DIE1: c_int = 158;
/// `S_PLAY_DIE2` thinker state (index 159).
pub const S_PLAY_DIE2: c_int = 159;
/// `S_PLAY_DIE3` thinker state (index 160).
pub const S_PLAY_DIE3: c_int = 160;
/// `S_PLAY_DIE4` thinker state (index 161).
pub const S_PLAY_DIE4: c_int = 161;
/// `S_PLAY_DIE5` thinker state (index 162).
pub const S_PLAY_DIE5: c_int = 162;
/// `S_PLAY_DIE6` thinker state (index 163).
pub const S_PLAY_DIE6: c_int = 163;
/// `S_PLAY_DIE7` thinker state (index 164).
pub const S_PLAY_DIE7: c_int = 164;
/// `S_PLAY_XDIE1` thinker state (index 165).
pub const S_PLAY_XDIE1: c_int = 165;
/// `S_PLAY_XDIE2` thinker state (index 166).
pub const S_PLAY_XDIE2: c_int = 166;
/// `S_PLAY_XDIE3` thinker state (index 167).
pub const S_PLAY_XDIE3: c_int = 167;
/// `S_PLAY_XDIE4` thinker state (index 168).
pub const S_PLAY_XDIE4: c_int = 168;
/// `S_PLAY_XDIE5` thinker state (index 169).
pub const S_PLAY_XDIE5: c_int = 169;
/// `S_PLAY_XDIE6` thinker state (index 170).
pub const S_PLAY_XDIE6: c_int = 170;
/// `S_PLAY_XDIE7` thinker state (index 171).
pub const S_PLAY_XDIE7: c_int = 171;
/// `S_PLAY_XDIE8` thinker state (index 172).
pub const S_PLAY_XDIE8: c_int = 172;
/// `S_PLAY_XDIE9` thinker state (index 173).
pub const S_PLAY_XDIE9: c_int = 173;
/// `S_POSS_STND` thinker state (index 174).
pub const S_POSS_STND: c_int = 174;
/// `S_POSS_STND2` thinker state (index 175).
pub const S_POSS_STND2: c_int = 175;
/// `S_POSS_RUN1` thinker state (index 176).
pub const S_POSS_RUN1: c_int = 176;
/// `S_POSS_RUN2` thinker state (index 177).
pub const S_POSS_RUN2: c_int = 177;
/// `S_POSS_RUN3` thinker state (index 178).
pub const S_POSS_RUN3: c_int = 178;
/// `S_POSS_RUN4` thinker state (index 179).
pub const S_POSS_RUN4: c_int = 179;
/// `S_POSS_RUN5` thinker state (index 180).
pub const S_POSS_RUN5: c_int = 180;
/// `S_POSS_RUN6` thinker state (index 181).
pub const S_POSS_RUN6: c_int = 181;
/// `S_POSS_RUN7` thinker state (index 182).
pub const S_POSS_RUN7: c_int = 182;
/// `S_POSS_RUN8` thinker state (index 183).
pub const S_POSS_RUN8: c_int = 183;
/// `S_POSS_ATK1` thinker state (index 184).
pub const S_POSS_ATK1: c_int = 184;
/// `S_POSS_ATK2` thinker state (index 185).
pub const S_POSS_ATK2: c_int = 185;
/// `S_POSS_ATK3` thinker state (index 186).
pub const S_POSS_ATK3: c_int = 186;
/// `S_POSS_PAIN` thinker state (index 187).
pub const S_POSS_PAIN: c_int = 187;
/// `S_POSS_PAIN2` thinker state (index 188).
pub const S_POSS_PAIN2: c_int = 188;
/// `S_POSS_DIE1` thinker state (index 189).
pub const S_POSS_DIE1: c_int = 189;
/// `S_POSS_DIE2` thinker state (index 190).
pub const S_POSS_DIE2: c_int = 190;
/// `S_POSS_DIE3` thinker state (index 191).
pub const S_POSS_DIE3: c_int = 191;
/// `S_POSS_DIE4` thinker state (index 192).
pub const S_POSS_DIE4: c_int = 192;
/// `S_POSS_DIE5` thinker state (index 193).
pub const S_POSS_DIE5: c_int = 193;
/// `S_POSS_XDIE1` thinker state (index 194).
pub const S_POSS_XDIE1: c_int = 194;
/// `S_POSS_XDIE2` thinker state (index 195).
pub const S_POSS_XDIE2: c_int = 195;
/// `S_POSS_XDIE3` thinker state (index 196).
pub const S_POSS_XDIE3: c_int = 196;
/// `S_POSS_XDIE4` thinker state (index 197).
pub const S_POSS_XDIE4: c_int = 197;
/// `S_POSS_XDIE5` thinker state (index 198).
pub const S_POSS_XDIE5: c_int = 198;
/// `S_POSS_XDIE6` thinker state (index 199).
pub const S_POSS_XDIE6: c_int = 199;
/// `S_POSS_XDIE7` thinker state (index 200).
pub const S_POSS_XDIE7: c_int = 200;
/// `S_POSS_XDIE8` thinker state (index 201).
pub const S_POSS_XDIE8: c_int = 201;
/// `S_POSS_XDIE9` thinker state (index 202).
pub const S_POSS_XDIE9: c_int = 202;
/// `S_POSS_RAISE1` thinker state (index 203).
pub const S_POSS_RAISE1: c_int = 203;
/// `S_POSS_RAISE2` thinker state (index 204).
pub const S_POSS_RAISE2: c_int = 204;
/// `S_POSS_RAISE3` thinker state (index 205).
pub const S_POSS_RAISE3: c_int = 205;
/// `S_POSS_RAISE4` thinker state (index 206).
pub const S_POSS_RAISE4: c_int = 206;
/// `S_SPOS_STND` thinker state (index 207).
pub const S_SPOS_STND: c_int = 207;
/// `S_SPOS_STND2` thinker state (index 208).
pub const S_SPOS_STND2: c_int = 208;
/// `S_SPOS_RUN1` thinker state (index 209).
pub const S_SPOS_RUN1: c_int = 209;
/// `S_SPOS_RUN2` thinker state (index 210).
pub const S_SPOS_RUN2: c_int = 210;
/// `S_SPOS_RUN3` thinker state (index 211).
pub const S_SPOS_RUN3: c_int = 211;
/// `S_SPOS_RUN4` thinker state (index 212).
pub const S_SPOS_RUN4: c_int = 212;
/// `S_SPOS_RUN5` thinker state (index 213).
pub const S_SPOS_RUN5: c_int = 213;
/// `S_SPOS_RUN6` thinker state (index 214).
pub const S_SPOS_RUN6: c_int = 214;
/// `S_SPOS_RUN7` thinker state (index 215).
pub const S_SPOS_RUN7: c_int = 215;
/// `S_SPOS_RUN8` thinker state (index 216).
pub const S_SPOS_RUN8: c_int = 216;
/// `S_SPOS_ATK1` thinker state (index 217).
pub const S_SPOS_ATK1: c_int = 217;
/// `S_SPOS_ATK2` thinker state (index 218).
pub const S_SPOS_ATK2: c_int = 218;
/// `S_SPOS_ATK3` thinker state (index 219).
pub const S_SPOS_ATK3: c_int = 219;
/// `S_SPOS_PAIN` thinker state (index 220).
pub const S_SPOS_PAIN: c_int = 220;
/// `S_SPOS_PAIN2` thinker state (index 221).
pub const S_SPOS_PAIN2: c_int = 221;
/// `S_SPOS_DIE1` thinker state (index 222).
pub const S_SPOS_DIE1: c_int = 222;
/// `S_SPOS_DIE2` thinker state (index 223).
pub const S_SPOS_DIE2: c_int = 223;
/// `S_SPOS_DIE3` thinker state (index 224).
pub const S_SPOS_DIE3: c_int = 224;
/// `S_SPOS_DIE4` thinker state (index 225).
pub const S_SPOS_DIE4: c_int = 225;
/// `S_SPOS_DIE5` thinker state (index 226).
pub const S_SPOS_DIE5: c_int = 226;
/// `S_SPOS_XDIE1` thinker state (index 227).
pub const S_SPOS_XDIE1: c_int = 227;
/// `S_SPOS_XDIE2` thinker state (index 228).
pub const S_SPOS_XDIE2: c_int = 228;
/// `S_SPOS_XDIE3` thinker state (index 229).
pub const S_SPOS_XDIE3: c_int = 229;
/// `S_SPOS_XDIE4` thinker state (index 230).
pub const S_SPOS_XDIE4: c_int = 230;
/// `S_SPOS_XDIE5` thinker state (index 231).
pub const S_SPOS_XDIE5: c_int = 231;
/// `S_SPOS_XDIE6` thinker state (index 232).
pub const S_SPOS_XDIE6: c_int = 232;
/// `S_SPOS_XDIE7` thinker state (index 233).
pub const S_SPOS_XDIE7: c_int = 233;
/// `S_SPOS_XDIE8` thinker state (index 234).
pub const S_SPOS_XDIE8: c_int = 234;
/// `S_SPOS_XDIE9` thinker state (index 235).
pub const S_SPOS_XDIE9: c_int = 235;
/// `S_SPOS_RAISE1` thinker state (index 236).
pub const S_SPOS_RAISE1: c_int = 236;
/// `S_SPOS_RAISE2` thinker state (index 237).
pub const S_SPOS_RAISE2: c_int = 237;
/// `S_SPOS_RAISE3` thinker state (index 238).
pub const S_SPOS_RAISE3: c_int = 238;
/// `S_SPOS_RAISE4` thinker state (index 239).
pub const S_SPOS_RAISE4: c_int = 239;
/// `S_SPOS_RAISE5` thinker state (index 240).
pub const S_SPOS_RAISE5: c_int = 240;
/// `S_VILE_STND` thinker state (index 241).
pub const S_VILE_STND: c_int = 241;
/// `S_VILE_STND2` thinker state (index 242).
pub const S_VILE_STND2: c_int = 242;
/// `S_VILE_RUN1` thinker state (index 243).
pub const S_VILE_RUN1: c_int = 243;
/// `S_VILE_RUN2` thinker state (index 244).
pub const S_VILE_RUN2: c_int = 244;
/// `S_VILE_RUN3` thinker state (index 245).
pub const S_VILE_RUN3: c_int = 245;
/// `S_VILE_RUN4` thinker state (index 246).
pub const S_VILE_RUN4: c_int = 246;
/// `S_VILE_RUN5` thinker state (index 247).
pub const S_VILE_RUN5: c_int = 247;
/// `S_VILE_RUN6` thinker state (index 248).
pub const S_VILE_RUN6: c_int = 248;
/// `S_VILE_RUN7` thinker state (index 249).
pub const S_VILE_RUN7: c_int = 249;
/// `S_VILE_RUN8` thinker state (index 250).
pub const S_VILE_RUN8: c_int = 250;
/// `S_VILE_RUN9` thinker state (index 251).
pub const S_VILE_RUN9: c_int = 251;
/// `S_VILE_RUN10` thinker state (index 252).
pub const S_VILE_RUN10: c_int = 252;
/// `S_VILE_RUN11` thinker state (index 253).
pub const S_VILE_RUN11: c_int = 253;
/// `S_VILE_RUN12` thinker state (index 254).
pub const S_VILE_RUN12: c_int = 254;
/// `S_VILE_ATK1` thinker state (index 255).
pub const S_VILE_ATK1: c_int = 255;
/// `S_VILE_ATK2` thinker state (index 256).
pub const S_VILE_ATK2: c_int = 256;
/// `S_VILE_ATK3` thinker state (index 257).
pub const S_VILE_ATK3: c_int = 257;
/// `S_VILE_ATK4` thinker state (index 258).
pub const S_VILE_ATK4: c_int = 258;
/// `S_VILE_ATK5` thinker state (index 259).
pub const S_VILE_ATK5: c_int = 259;
/// `S_VILE_ATK6` thinker state (index 260).
pub const S_VILE_ATK6: c_int = 260;
/// `S_VILE_ATK7` thinker state (index 261).
pub const S_VILE_ATK7: c_int = 261;
/// `S_VILE_ATK8` thinker state (index 262).
pub const S_VILE_ATK8: c_int = 262;
/// `S_VILE_ATK9` thinker state (index 263).
pub const S_VILE_ATK9: c_int = 263;
/// `S_VILE_ATK10` thinker state (index 264).
pub const S_VILE_ATK10: c_int = 264;
/// `S_VILE_ATK11` thinker state (index 265).
pub const S_VILE_ATK11: c_int = 265;
/// `S_VILE_HEAL1` thinker state (index 266).
pub const S_VILE_HEAL1: c_int = 266;
/// `S_VILE_HEAL2` thinker state (index 267).
pub const S_VILE_HEAL2: c_int = 267;
/// `S_VILE_HEAL3` thinker state (index 268).
pub const S_VILE_HEAL3: c_int = 268;
/// `S_VILE_PAIN` thinker state (index 269).
pub const S_VILE_PAIN: c_int = 269;
/// `S_VILE_PAIN2` thinker state (index 270).
pub const S_VILE_PAIN2: c_int = 270;
/// `S_VILE_DIE1` thinker state (index 271).
pub const S_VILE_DIE1: c_int = 271;
/// `S_VILE_DIE2` thinker state (index 272).
pub const S_VILE_DIE2: c_int = 272;
/// `S_VILE_DIE3` thinker state (index 273).
pub const S_VILE_DIE3: c_int = 273;
/// `S_VILE_DIE4` thinker state (index 274).
pub const S_VILE_DIE4: c_int = 274;
/// `S_VILE_DIE5` thinker state (index 275).
pub const S_VILE_DIE5: c_int = 275;
/// `S_VILE_DIE6` thinker state (index 276).
pub const S_VILE_DIE6: c_int = 276;
/// `S_VILE_DIE7` thinker state (index 277).
pub const S_VILE_DIE7: c_int = 277;
/// `S_VILE_DIE8` thinker state (index 278).
pub const S_VILE_DIE8: c_int = 278;
/// `S_VILE_DIE9` thinker state (index 279).
pub const S_VILE_DIE9: c_int = 279;
/// `S_VILE_DIE10` thinker state (index 280).
pub const S_VILE_DIE10: c_int = 280;
/// `S_FIRE1` thinker state (index 281).
pub const S_FIRE1: c_int = 281;
/// `S_FIRE2` thinker state (index 282).
pub const S_FIRE2: c_int = 282;
/// `S_FIRE3` thinker state (index 283).
pub const S_FIRE3: c_int = 283;
/// `S_FIRE4` thinker state (index 284).
pub const S_FIRE4: c_int = 284;
/// `S_FIRE5` thinker state (index 285).
pub const S_FIRE5: c_int = 285;
/// `S_FIRE6` thinker state (index 286).
pub const S_FIRE6: c_int = 286;
/// `S_FIRE7` thinker state (index 287).
pub const S_FIRE7: c_int = 287;
/// `S_FIRE8` thinker state (index 288).
pub const S_FIRE8: c_int = 288;
/// `S_FIRE9` thinker state (index 289).
pub const S_FIRE9: c_int = 289;
/// `S_FIRE10` thinker state (index 290).
pub const S_FIRE10: c_int = 290;
/// `S_FIRE11` thinker state (index 291).
pub const S_FIRE11: c_int = 291;
/// `S_FIRE12` thinker state (index 292).
pub const S_FIRE12: c_int = 292;
/// `S_FIRE13` thinker state (index 293).
pub const S_FIRE13: c_int = 293;
/// `S_FIRE14` thinker state (index 294).
pub const S_FIRE14: c_int = 294;
/// `S_FIRE15` thinker state (index 295).
pub const S_FIRE15: c_int = 295;
/// `S_FIRE16` thinker state (index 296).
pub const S_FIRE16: c_int = 296;
/// `S_FIRE17` thinker state (index 297).
pub const S_FIRE17: c_int = 297;
/// `S_FIRE18` thinker state (index 298).
pub const S_FIRE18: c_int = 298;
/// `S_FIRE19` thinker state (index 299).
pub const S_FIRE19: c_int = 299;
/// `S_FIRE20` thinker state (index 300).
pub const S_FIRE20: c_int = 300;
/// `S_FIRE21` thinker state (index 301).
pub const S_FIRE21: c_int = 301;
/// `S_FIRE22` thinker state (index 302).
pub const S_FIRE22: c_int = 302;
/// `S_FIRE23` thinker state (index 303).
pub const S_FIRE23: c_int = 303;
/// `S_FIRE24` thinker state (index 304).
pub const S_FIRE24: c_int = 304;
/// `S_FIRE25` thinker state (index 305).
pub const S_FIRE25: c_int = 305;
/// `S_FIRE26` thinker state (index 306).
pub const S_FIRE26: c_int = 306;
/// `S_FIRE27` thinker state (index 307).
pub const S_FIRE27: c_int = 307;
/// `S_FIRE28` thinker state (index 308).
pub const S_FIRE28: c_int = 308;
/// `S_FIRE29` thinker state (index 309).
pub const S_FIRE29: c_int = 309;
/// `S_FIRE30` thinker state (index 310).
pub const S_FIRE30: c_int = 310;
/// `S_SMOKE1` thinker state (index 311).
pub const S_SMOKE1: c_int = 311;
/// `S_SMOKE2` thinker state (index 312).
pub const S_SMOKE2: c_int = 312;
/// `S_SMOKE3` thinker state (index 313).
pub const S_SMOKE3: c_int = 313;
/// `S_SMOKE4` thinker state (index 314).
pub const S_SMOKE4: c_int = 314;
/// `S_SMOKE5` thinker state (index 315).
pub const S_SMOKE5: c_int = 315;
/// `S_TRACER` thinker state (index 316).
pub const S_TRACER: c_int = 316;
/// `S_TRACER2` thinker state (index 317).
pub const S_TRACER2: c_int = 317;
/// `S_TRACEEXP1` thinker state (index 318).
pub const S_TRACEEXP1: c_int = 318;
/// `S_TRACEEXP2` thinker state (index 319).
pub const S_TRACEEXP2: c_int = 319;
/// `S_TRACEEXP3` thinker state (index 320).
pub const S_TRACEEXP3: c_int = 320;
/// `S_SKEL_STND` thinker state (index 321).
pub const S_SKEL_STND: c_int = 321;
/// `S_SKEL_STND2` thinker state (index 322).
pub const S_SKEL_STND2: c_int = 322;
/// `S_SKEL_RUN1` thinker state (index 323).
pub const S_SKEL_RUN1: c_int = 323;
/// `S_SKEL_RUN2` thinker state (index 324).
pub const S_SKEL_RUN2: c_int = 324;
/// `S_SKEL_RUN3` thinker state (index 325).
pub const S_SKEL_RUN3: c_int = 325;
/// `S_SKEL_RUN4` thinker state (index 326).
pub const S_SKEL_RUN4: c_int = 326;
/// `S_SKEL_RUN5` thinker state (index 327).
pub const S_SKEL_RUN5: c_int = 327;
/// `S_SKEL_RUN6` thinker state (index 328).
pub const S_SKEL_RUN6: c_int = 328;
/// `S_SKEL_RUN7` thinker state (index 329).
pub const S_SKEL_RUN7: c_int = 329;
/// `S_SKEL_RUN8` thinker state (index 330).
pub const S_SKEL_RUN8: c_int = 330;
/// `S_SKEL_RUN9` thinker state (index 331).
pub const S_SKEL_RUN9: c_int = 331;
/// `S_SKEL_RUN10` thinker state (index 332).
pub const S_SKEL_RUN10: c_int = 332;
/// `S_SKEL_RUN11` thinker state (index 333).
pub const S_SKEL_RUN11: c_int = 333;
/// `S_SKEL_RUN12` thinker state (index 334).
pub const S_SKEL_RUN12: c_int = 334;
/// `S_SKEL_FIST1` thinker state (index 335).
pub const S_SKEL_FIST1: c_int = 335;
/// `S_SKEL_FIST2` thinker state (index 336).
pub const S_SKEL_FIST2: c_int = 336;
/// `S_SKEL_FIST3` thinker state (index 337).
pub const S_SKEL_FIST3: c_int = 337;
/// `S_SKEL_FIST4` thinker state (index 338).
pub const S_SKEL_FIST4: c_int = 338;
/// `S_SKEL_MISS1` thinker state (index 339).
pub const S_SKEL_MISS1: c_int = 339;
/// `S_SKEL_MISS2` thinker state (index 340).
pub const S_SKEL_MISS2: c_int = 340;
/// `S_SKEL_MISS3` thinker state (index 341).
pub const S_SKEL_MISS3: c_int = 341;
/// `S_SKEL_MISS4` thinker state (index 342).
pub const S_SKEL_MISS4: c_int = 342;
/// `S_SKEL_PAIN` thinker state (index 343).
pub const S_SKEL_PAIN: c_int = 343;
/// `S_SKEL_PAIN2` thinker state (index 344).
pub const S_SKEL_PAIN2: c_int = 344;
/// `S_SKEL_DIE1` thinker state (index 345).
pub const S_SKEL_DIE1: c_int = 345;
/// `S_SKEL_DIE2` thinker state (index 346).
pub const S_SKEL_DIE2: c_int = 346;
/// `S_SKEL_DIE3` thinker state (index 347).
pub const S_SKEL_DIE3: c_int = 347;
/// `S_SKEL_DIE4` thinker state (index 348).
pub const S_SKEL_DIE4: c_int = 348;
/// `S_SKEL_DIE5` thinker state (index 349).
pub const S_SKEL_DIE5: c_int = 349;
/// `S_SKEL_DIE6` thinker state (index 350).
pub const S_SKEL_DIE6: c_int = 350;
/// `S_SKEL_RAISE1` thinker state (index 351).
pub const S_SKEL_RAISE1: c_int = 351;
/// `S_SKEL_RAISE2` thinker state (index 352).
pub const S_SKEL_RAISE2: c_int = 352;
/// `S_SKEL_RAISE3` thinker state (index 353).
pub const S_SKEL_RAISE3: c_int = 353;
/// `S_SKEL_RAISE4` thinker state (index 354).
pub const S_SKEL_RAISE4: c_int = 354;
/// `S_SKEL_RAISE5` thinker state (index 355).
pub const S_SKEL_RAISE5: c_int = 355;
/// `S_SKEL_RAISE6` thinker state (index 356).
pub const S_SKEL_RAISE6: c_int = 356;
/// `S_FATSHOT1` thinker state (index 357).
pub const S_FATSHOT1: c_int = 357;
/// `S_FATSHOT2` thinker state (index 358).
pub const S_FATSHOT2: c_int = 358;
/// `S_FATSHOTX1` thinker state (index 359).
pub const S_FATSHOTX1: c_int = 359;
/// `S_FATSHOTX2` thinker state (index 360).
pub const S_FATSHOTX2: c_int = 360;
/// `S_FATSHOTX3` thinker state (index 361).
pub const S_FATSHOTX3: c_int = 361;
/// `S_FATT_STND` thinker state (index 362).
pub const S_FATT_STND: c_int = 362;
/// `S_FATT_STND2` thinker state (index 363).
pub const S_FATT_STND2: c_int = 363;
/// `S_FATT_RUN1` thinker state (index 364).
pub const S_FATT_RUN1: c_int = 364;
/// `S_FATT_RUN2` thinker state (index 365).
pub const S_FATT_RUN2: c_int = 365;
/// `S_FATT_RUN3` thinker state (index 366).
pub const S_FATT_RUN3: c_int = 366;
/// `S_FATT_RUN4` thinker state (index 367).
pub const S_FATT_RUN4: c_int = 367;
/// `S_FATT_RUN5` thinker state (index 368).
pub const S_FATT_RUN5: c_int = 368;
/// `S_FATT_RUN6` thinker state (index 369).
pub const S_FATT_RUN6: c_int = 369;
/// `S_FATT_RUN7` thinker state (index 370).
pub const S_FATT_RUN7: c_int = 370;
/// `S_FATT_RUN8` thinker state (index 371).
pub const S_FATT_RUN8: c_int = 371;
/// `S_FATT_RUN9` thinker state (index 372).
pub const S_FATT_RUN9: c_int = 372;
/// `S_FATT_RUN10` thinker state (index 373).
pub const S_FATT_RUN10: c_int = 373;
/// `S_FATT_RUN11` thinker state (index 374).
pub const S_FATT_RUN11: c_int = 374;
/// `S_FATT_RUN12` thinker state (index 375).
pub const S_FATT_RUN12: c_int = 375;
/// `S_FATT_ATK1` thinker state (index 376).
pub const S_FATT_ATK1: c_int = 376;
/// `S_FATT_ATK2` thinker state (index 377).
pub const S_FATT_ATK2: c_int = 377;
/// `S_FATT_ATK3` thinker state (index 378).
pub const S_FATT_ATK3: c_int = 378;
/// `S_FATT_ATK4` thinker state (index 379).
pub const S_FATT_ATK4: c_int = 379;
/// `S_FATT_ATK5` thinker state (index 380).
pub const S_FATT_ATK5: c_int = 380;
/// `S_FATT_ATK6` thinker state (index 381).
pub const S_FATT_ATK6: c_int = 381;
/// `S_FATT_ATK7` thinker state (index 382).
pub const S_FATT_ATK7: c_int = 382;
/// `S_FATT_ATK8` thinker state (index 383).
pub const S_FATT_ATK8: c_int = 383;
/// `S_FATT_ATK9` thinker state (index 384).
pub const S_FATT_ATK9: c_int = 384;
/// `S_FATT_ATK10` thinker state (index 385).
pub const S_FATT_ATK10: c_int = 385;
/// `S_FATT_PAIN` thinker state (index 386).
pub const S_FATT_PAIN: c_int = 386;
/// `S_FATT_PAIN2` thinker state (index 387).
pub const S_FATT_PAIN2: c_int = 387;
/// `S_FATT_DIE1` thinker state (index 388).
pub const S_FATT_DIE1: c_int = 388;
/// `S_FATT_DIE2` thinker state (index 389).
pub const S_FATT_DIE2: c_int = 389;
/// `S_FATT_DIE3` thinker state (index 390).
pub const S_FATT_DIE3: c_int = 390;
/// `S_FATT_DIE4` thinker state (index 391).
pub const S_FATT_DIE4: c_int = 391;
/// `S_FATT_DIE5` thinker state (index 392).
pub const S_FATT_DIE5: c_int = 392;
/// `S_FATT_DIE6` thinker state (index 393).
pub const S_FATT_DIE6: c_int = 393;
/// `S_FATT_DIE7` thinker state (index 394).
pub const S_FATT_DIE7: c_int = 394;
/// `S_FATT_DIE8` thinker state (index 395).
pub const S_FATT_DIE8: c_int = 395;
/// `S_FATT_DIE9` thinker state (index 396).
pub const S_FATT_DIE9: c_int = 396;
/// `S_FATT_DIE10` thinker state (index 397).
pub const S_FATT_DIE10: c_int = 397;
/// `S_FATT_RAISE1` thinker state (index 398).
pub const S_FATT_RAISE1: c_int = 398;
/// `S_FATT_RAISE2` thinker state (index 399).
pub const S_FATT_RAISE2: c_int = 399;
/// `S_FATT_RAISE3` thinker state (index 400).
pub const S_FATT_RAISE3: c_int = 400;
/// `S_FATT_RAISE4` thinker state (index 401).
pub const S_FATT_RAISE4: c_int = 401;
/// `S_FATT_RAISE5` thinker state (index 402).
pub const S_FATT_RAISE5: c_int = 402;
/// `S_FATT_RAISE6` thinker state (index 403).
pub const S_FATT_RAISE6: c_int = 403;
/// `S_FATT_RAISE7` thinker state (index 404).
pub const S_FATT_RAISE7: c_int = 404;
/// `S_FATT_RAISE8` thinker state (index 405).
pub const S_FATT_RAISE8: c_int = 405;
/// `S_CPOS_STND` thinker state (index 406).
pub const S_CPOS_STND: c_int = 406;
/// `S_CPOS_STND2` thinker state (index 407).
pub const S_CPOS_STND2: c_int = 407;
/// `S_CPOS_RUN1` thinker state (index 408).
pub const S_CPOS_RUN1: c_int = 408;
/// `S_CPOS_RUN2` thinker state (index 409).
pub const S_CPOS_RUN2: c_int = 409;
/// `S_CPOS_RUN3` thinker state (index 410).
pub const S_CPOS_RUN3: c_int = 410;
/// `S_CPOS_RUN4` thinker state (index 411).
pub const S_CPOS_RUN4: c_int = 411;
/// `S_CPOS_RUN5` thinker state (index 412).
pub const S_CPOS_RUN5: c_int = 412;
/// `S_CPOS_RUN6` thinker state (index 413).
pub const S_CPOS_RUN6: c_int = 413;
/// `S_CPOS_RUN7` thinker state (index 414).
pub const S_CPOS_RUN7: c_int = 414;
/// `S_CPOS_RUN8` thinker state (index 415).
pub const S_CPOS_RUN8: c_int = 415;
/// `S_CPOS_ATK1` thinker state (index 416).
pub const S_CPOS_ATK1: c_int = 416;
/// `S_CPOS_ATK2` thinker state (index 417).
pub const S_CPOS_ATK2: c_int = 417;
/// `S_CPOS_ATK3` thinker state (index 418).
pub const S_CPOS_ATK3: c_int = 418;
/// `S_CPOS_ATK4` thinker state (index 419).
pub const S_CPOS_ATK4: c_int = 419;
/// `S_CPOS_PAIN` thinker state (index 420).
pub const S_CPOS_PAIN: c_int = 420;
/// `S_CPOS_PAIN2` thinker state (index 421).
pub const S_CPOS_PAIN2: c_int = 421;
/// `S_CPOS_DIE1` thinker state (index 422).
pub const S_CPOS_DIE1: c_int = 422;
/// `S_CPOS_DIE2` thinker state (index 423).
pub const S_CPOS_DIE2: c_int = 423;
/// `S_CPOS_DIE3` thinker state (index 424).
pub const S_CPOS_DIE3: c_int = 424;
/// `S_CPOS_DIE4` thinker state (index 425).
pub const S_CPOS_DIE4: c_int = 425;
/// `S_CPOS_DIE5` thinker state (index 426).
pub const S_CPOS_DIE5: c_int = 426;
/// `S_CPOS_DIE6` thinker state (index 427).
pub const S_CPOS_DIE6: c_int = 427;
/// `S_CPOS_DIE7` thinker state (index 428).
pub const S_CPOS_DIE7: c_int = 428;
/// `S_CPOS_XDIE1` thinker state (index 429).
pub const S_CPOS_XDIE1: c_int = 429;
/// `S_CPOS_XDIE2` thinker state (index 430).
pub const S_CPOS_XDIE2: c_int = 430;
/// `S_CPOS_XDIE3` thinker state (index 431).
pub const S_CPOS_XDIE3: c_int = 431;
/// `S_CPOS_XDIE4` thinker state (index 432).
pub const S_CPOS_XDIE4: c_int = 432;
/// `S_CPOS_XDIE5` thinker state (index 433).
pub const S_CPOS_XDIE5: c_int = 433;
/// `S_CPOS_XDIE6` thinker state (index 434).
pub const S_CPOS_XDIE6: c_int = 434;
/// `S_CPOS_RAISE1` thinker state (index 435).
pub const S_CPOS_RAISE1: c_int = 435;
/// `S_CPOS_RAISE2` thinker state (index 436).
pub const S_CPOS_RAISE2: c_int = 436;
/// `S_CPOS_RAISE3` thinker state (index 437).
pub const S_CPOS_RAISE3: c_int = 437;
/// `S_CPOS_RAISE4` thinker state (index 438).
pub const S_CPOS_RAISE4: c_int = 438;
/// `S_CPOS_RAISE5` thinker state (index 439).
pub const S_CPOS_RAISE5: c_int = 439;
/// `S_CPOS_RAISE6` thinker state (index 440).
pub const S_CPOS_RAISE6: c_int = 440;
/// `S_CPOS_RAISE7` thinker state (index 441).
pub const S_CPOS_RAISE7: c_int = 441;
/// `S_TROO_STND` thinker state (index 442).
pub const S_TROO_STND: c_int = 442;
/// `S_TROO_STND2` thinker state (index 443).
pub const S_TROO_STND2: c_int = 443;
/// `S_TROO_RUN1` thinker state (index 444).
pub const S_TROO_RUN1: c_int = 444;
/// `S_TROO_RUN2` thinker state (index 445).
pub const S_TROO_RUN2: c_int = 445;
/// `S_TROO_RUN3` thinker state (index 446).
pub const S_TROO_RUN3: c_int = 446;
/// `S_TROO_RUN4` thinker state (index 447).
pub const S_TROO_RUN4: c_int = 447;
/// `S_TROO_RUN5` thinker state (index 448).
pub const S_TROO_RUN5: c_int = 448;
/// `S_TROO_RUN6` thinker state (index 449).
pub const S_TROO_RUN6: c_int = 449;
/// `S_TROO_RUN7` thinker state (index 450).
pub const S_TROO_RUN7: c_int = 450;
/// `S_TROO_RUN8` thinker state (index 451).
pub const S_TROO_RUN8: c_int = 451;
/// `S_TROO_ATK1` thinker state (index 452).
pub const S_TROO_ATK1: c_int = 452;
/// `S_TROO_ATK2` thinker state (index 453).
pub const S_TROO_ATK2: c_int = 453;
/// `S_TROO_ATK3` thinker state (index 454).
pub const S_TROO_ATK3: c_int = 454;
/// `S_TROO_PAIN` thinker state (index 455).
pub const S_TROO_PAIN: c_int = 455;
/// `S_TROO_PAIN2` thinker state (index 456).
pub const S_TROO_PAIN2: c_int = 456;
/// `S_TROO_DIE1` thinker state (index 457).
pub const S_TROO_DIE1: c_int = 457;
/// `S_TROO_DIE2` thinker state (index 458).
pub const S_TROO_DIE2: c_int = 458;
/// `S_TROO_DIE3` thinker state (index 459).
pub const S_TROO_DIE3: c_int = 459;
/// `S_TROO_DIE4` thinker state (index 460).
pub const S_TROO_DIE4: c_int = 460;
/// `S_TROO_DIE5` thinker state (index 461).
pub const S_TROO_DIE5: c_int = 461;
/// `S_TROO_XDIE1` thinker state (index 462).
pub const S_TROO_XDIE1: c_int = 462;
/// `S_TROO_XDIE2` thinker state (index 463).
pub const S_TROO_XDIE2: c_int = 463;
/// `S_TROO_XDIE3` thinker state (index 464).
pub const S_TROO_XDIE3: c_int = 464;
/// `S_TROO_XDIE4` thinker state (index 465).
pub const S_TROO_XDIE4: c_int = 465;
/// `S_TROO_XDIE5` thinker state (index 466).
pub const S_TROO_XDIE5: c_int = 466;
/// `S_TROO_XDIE6` thinker state (index 467).
pub const S_TROO_XDIE6: c_int = 467;
/// `S_TROO_XDIE7` thinker state (index 468).
pub const S_TROO_XDIE7: c_int = 468;
/// `S_TROO_XDIE8` thinker state (index 469).
pub const S_TROO_XDIE8: c_int = 469;
/// `S_TROO_RAISE1` thinker state (index 470).
pub const S_TROO_RAISE1: c_int = 470;
/// `S_TROO_RAISE2` thinker state (index 471).
pub const S_TROO_RAISE2: c_int = 471;
/// `S_TROO_RAISE3` thinker state (index 472).
pub const S_TROO_RAISE3: c_int = 472;
/// `S_TROO_RAISE4` thinker state (index 473).
pub const S_TROO_RAISE4: c_int = 473;
/// `S_TROO_RAISE5` thinker state (index 474).
pub const S_TROO_RAISE5: c_int = 474;
/// `S_SARG_STND` thinker state (index 475).
pub const S_SARG_STND: c_int = 475;
/// `S_SARG_STND2` thinker state (index 476).
pub const S_SARG_STND2: c_int = 476;
/// `S_SARG_RUN1` thinker state (index 477).
pub const S_SARG_RUN1: c_int = 477;
/// `S_SARG_RUN2` thinker state (index 478).
pub const S_SARG_RUN2: c_int = 478;
/// `S_SARG_RUN3` thinker state (index 479).
pub const S_SARG_RUN3: c_int = 479;
/// `S_SARG_RUN4` thinker state (index 480).
pub const S_SARG_RUN4: c_int = 480;
/// `S_SARG_RUN5` thinker state (index 481).
pub const S_SARG_RUN5: c_int = 481;
/// `S_SARG_RUN6` thinker state (index 482).
pub const S_SARG_RUN6: c_int = 482;
/// `S_SARG_RUN7` thinker state (index 483).
pub const S_SARG_RUN7: c_int = 483;
/// `S_SARG_RUN8` thinker state (index 484).
pub const S_SARG_RUN8: c_int = 484;
/// `S_SARG_ATK1` thinker state (index 485).
pub const S_SARG_ATK1: c_int = 485;
/// `S_SARG_ATK2` thinker state (index 486).
pub const S_SARG_ATK2: c_int = 486;
/// `S_SARG_ATK3` thinker state (index 487).
pub const S_SARG_ATK3: c_int = 487;
/// `S_SARG_PAIN` thinker state (index 488).
pub const S_SARG_PAIN: c_int = 488;
/// `S_SARG_PAIN2` thinker state (index 489).
pub const S_SARG_PAIN2: c_int = 489;
/// `S_SARG_DIE1` thinker state (index 490).
pub const S_SARG_DIE1: c_int = 490;
/// `S_SARG_DIE2` thinker state (index 491).
pub const S_SARG_DIE2: c_int = 491;
/// `S_SARG_DIE3` thinker state (index 492).
pub const S_SARG_DIE3: c_int = 492;
/// `S_SARG_DIE4` thinker state (index 493).
pub const S_SARG_DIE4: c_int = 493;
/// `S_SARG_DIE5` thinker state (index 494).
pub const S_SARG_DIE5: c_int = 494;
/// `S_SARG_DIE6` thinker state (index 495).
pub const S_SARG_DIE6: c_int = 495;
/// `S_SARG_RAISE1` thinker state (index 496).
pub const S_SARG_RAISE1: c_int = 496;
/// `S_SARG_RAISE2` thinker state (index 497).
pub const S_SARG_RAISE2: c_int = 497;
/// `S_SARG_RAISE3` thinker state (index 498).
pub const S_SARG_RAISE3: c_int = 498;
/// `S_SARG_RAISE4` thinker state (index 499).
pub const S_SARG_RAISE4: c_int = 499;
/// `S_SARG_RAISE5` thinker state (index 500).
pub const S_SARG_RAISE5: c_int = 500;
/// `S_SARG_RAISE6` thinker state (index 501).
pub const S_SARG_RAISE6: c_int = 501;
/// `S_HEAD_STND` thinker state (index 502).
pub const S_HEAD_STND: c_int = 502;
/// `S_HEAD_RUN1` thinker state (index 503).
pub const S_HEAD_RUN1: c_int = 503;
/// `S_HEAD_ATK1` thinker state (index 504).
pub const S_HEAD_ATK1: c_int = 504;
/// `S_HEAD_ATK2` thinker state (index 505).
pub const S_HEAD_ATK2: c_int = 505;
/// `S_HEAD_ATK3` thinker state (index 506).
pub const S_HEAD_ATK3: c_int = 506;
/// `S_HEAD_PAIN` thinker state (index 507).
pub const S_HEAD_PAIN: c_int = 507;
/// `S_HEAD_PAIN2` thinker state (index 508).
pub const S_HEAD_PAIN2: c_int = 508;
/// `S_HEAD_PAIN3` thinker state (index 509).
pub const S_HEAD_PAIN3: c_int = 509;
/// `S_HEAD_DIE1` thinker state (index 510).
pub const S_HEAD_DIE1: c_int = 510;
/// `S_HEAD_DIE2` thinker state (index 511).
pub const S_HEAD_DIE2: c_int = 511;
/// `S_HEAD_DIE3` thinker state (index 512).
pub const S_HEAD_DIE3: c_int = 512;
/// `S_HEAD_DIE4` thinker state (index 513).
pub const S_HEAD_DIE4: c_int = 513;
/// `S_HEAD_DIE5` thinker state (index 514).
pub const S_HEAD_DIE5: c_int = 514;
/// `S_HEAD_DIE6` thinker state (index 515).
pub const S_HEAD_DIE6: c_int = 515;
/// `S_HEAD_RAISE1` thinker state (index 516).
pub const S_HEAD_RAISE1: c_int = 516;
/// `S_HEAD_RAISE2` thinker state (index 517).
pub const S_HEAD_RAISE2: c_int = 517;
/// `S_HEAD_RAISE3` thinker state (index 518).
pub const S_HEAD_RAISE3: c_int = 518;
/// `S_HEAD_RAISE4` thinker state (index 519).
pub const S_HEAD_RAISE4: c_int = 519;
/// `S_HEAD_RAISE5` thinker state (index 520).
pub const S_HEAD_RAISE5: c_int = 520;
/// `S_HEAD_RAISE6` thinker state (index 521).
pub const S_HEAD_RAISE6: c_int = 521;
/// `S_BRBALL1` thinker state (index 522).
pub const S_BRBALL1: c_int = 522;
/// `S_BRBALL2` thinker state (index 523).
pub const S_BRBALL2: c_int = 523;
/// `S_BRBALLX1` thinker state (index 524).
pub const S_BRBALLX1: c_int = 524;
/// `S_BRBALLX2` thinker state (index 525).
pub const S_BRBALLX2: c_int = 525;
/// `S_BRBALLX3` thinker state (index 526).
pub const S_BRBALLX3: c_int = 526;
/// `S_BOSS_STND` thinker state (index 527).
pub const S_BOSS_STND: c_int = 527;
/// `S_BOSS_STND2` thinker state (index 528).
pub const S_BOSS_STND2: c_int = 528;
/// `S_BOSS_RUN1` thinker state (index 529).
pub const S_BOSS_RUN1: c_int = 529;
/// `S_BOSS_RUN2` thinker state (index 530).
pub const S_BOSS_RUN2: c_int = 530;
/// `S_BOSS_RUN3` thinker state (index 531).
pub const S_BOSS_RUN3: c_int = 531;
/// `S_BOSS_RUN4` thinker state (index 532).
pub const S_BOSS_RUN4: c_int = 532;
/// `S_BOSS_RUN5` thinker state (index 533).
pub const S_BOSS_RUN5: c_int = 533;
/// `S_BOSS_RUN6` thinker state (index 534).
pub const S_BOSS_RUN6: c_int = 534;
/// `S_BOSS_RUN7` thinker state (index 535).
pub const S_BOSS_RUN7: c_int = 535;
/// `S_BOSS_RUN8` thinker state (index 536).
pub const S_BOSS_RUN8: c_int = 536;
/// `S_BOSS_ATK1` thinker state (index 537).
pub const S_BOSS_ATK1: c_int = 537;
/// `S_BOSS_ATK2` thinker state (index 538).
pub const S_BOSS_ATK2: c_int = 538;
/// `S_BOSS_ATK3` thinker state (index 539).
pub const S_BOSS_ATK3: c_int = 539;
/// `S_BOSS_PAIN` thinker state (index 540).
pub const S_BOSS_PAIN: c_int = 540;
/// `S_BOSS_PAIN2` thinker state (index 541).
pub const S_BOSS_PAIN2: c_int = 541;
/// `S_BOSS_DIE1` thinker state (index 542).
pub const S_BOSS_DIE1: c_int = 542;
/// `S_BOSS_DIE2` thinker state (index 543).
pub const S_BOSS_DIE2: c_int = 543;
/// `S_BOSS_DIE3` thinker state (index 544).
pub const S_BOSS_DIE3: c_int = 544;
/// `S_BOSS_DIE4` thinker state (index 545).
pub const S_BOSS_DIE4: c_int = 545;
/// `S_BOSS_DIE5` thinker state (index 546).
pub const S_BOSS_DIE5: c_int = 546;
/// `S_BOSS_DIE6` thinker state (index 547).
pub const S_BOSS_DIE6: c_int = 547;
/// `S_BOSS_DIE7` thinker state (index 548).
pub const S_BOSS_DIE7: c_int = 548;
/// `S_BOSS_RAISE1` thinker state (index 549).
pub const S_BOSS_RAISE1: c_int = 549;
/// `S_BOSS_RAISE2` thinker state (index 550).
pub const S_BOSS_RAISE2: c_int = 550;
/// `S_BOSS_RAISE3` thinker state (index 551).
pub const S_BOSS_RAISE3: c_int = 551;
/// `S_BOSS_RAISE4` thinker state (index 552).
pub const S_BOSS_RAISE4: c_int = 552;
/// `S_BOSS_RAISE5` thinker state (index 553).
pub const S_BOSS_RAISE5: c_int = 553;
/// `S_BOSS_RAISE6` thinker state (index 554).
pub const S_BOSS_RAISE6: c_int = 554;
/// `S_BOSS_RAISE7` thinker state (index 555).
pub const S_BOSS_RAISE7: c_int = 555;
/// `S_BOS2_STND` thinker state (index 556).
pub const S_BOS2_STND: c_int = 556;
/// `S_BOS2_STND2` thinker state (index 557).
pub const S_BOS2_STND2: c_int = 557;
/// `S_BOS2_RUN1` thinker state (index 558).
pub const S_BOS2_RUN1: c_int = 558;
/// `S_BOS2_RUN2` thinker state (index 559).
pub const S_BOS2_RUN2: c_int = 559;
/// `S_BOS2_RUN3` thinker state (index 560).
pub const S_BOS2_RUN3: c_int = 560;
/// `S_BOS2_RUN4` thinker state (index 561).
pub const S_BOS2_RUN4: c_int = 561;
/// `S_BOS2_RUN5` thinker state (index 562).
pub const S_BOS2_RUN5: c_int = 562;
/// `S_BOS2_RUN6` thinker state (index 563).
pub const S_BOS2_RUN6: c_int = 563;
/// `S_BOS2_RUN7` thinker state (index 564).
pub const S_BOS2_RUN7: c_int = 564;
/// `S_BOS2_RUN8` thinker state (index 565).
pub const S_BOS2_RUN8: c_int = 565;
/// `S_BOS2_ATK1` thinker state (index 566).
pub const S_BOS2_ATK1: c_int = 566;
/// `S_BOS2_ATK2` thinker state (index 567).
pub const S_BOS2_ATK2: c_int = 567;
/// `S_BOS2_ATK3` thinker state (index 568).
pub const S_BOS2_ATK3: c_int = 568;
/// `S_BOS2_PAIN` thinker state (index 569).
pub const S_BOS2_PAIN: c_int = 569;
/// `S_BOS2_PAIN2` thinker state (index 570).
pub const S_BOS2_PAIN2: c_int = 570;
/// `S_BOS2_DIE1` thinker state (index 571).
pub const S_BOS2_DIE1: c_int = 571;
/// `S_BOS2_DIE2` thinker state (index 572).
pub const S_BOS2_DIE2: c_int = 572;
/// `S_BOS2_DIE3` thinker state (index 573).
pub const S_BOS2_DIE3: c_int = 573;
/// `S_BOS2_DIE4` thinker state (index 574).
pub const S_BOS2_DIE4: c_int = 574;
/// `S_BOS2_DIE5` thinker state (index 575).
pub const S_BOS2_DIE5: c_int = 575;
/// `S_BOS2_DIE6` thinker state (index 576).
pub const S_BOS2_DIE6: c_int = 576;
/// `S_BOS2_DIE7` thinker state (index 577).
pub const S_BOS2_DIE7: c_int = 577;
/// `S_BOS2_RAISE1` thinker state (index 578).
pub const S_BOS2_RAISE1: c_int = 578;
/// `S_BOS2_RAISE2` thinker state (index 579).
pub const S_BOS2_RAISE2: c_int = 579;
/// `S_BOS2_RAISE3` thinker state (index 580).
pub const S_BOS2_RAISE3: c_int = 580;
/// `S_BOS2_RAISE4` thinker state (index 581).
pub const S_BOS2_RAISE4: c_int = 581;
/// `S_BOS2_RAISE5` thinker state (index 582).
pub const S_BOS2_RAISE5: c_int = 582;
/// `S_BOS2_RAISE6` thinker state (index 583).
pub const S_BOS2_RAISE6: c_int = 583;
/// `S_BOS2_RAISE7` thinker state (index 584).
pub const S_BOS2_RAISE7: c_int = 584;
/// `S_SKULL_STND` thinker state (index 585).
pub const S_SKULL_STND: c_int = 585;
/// `S_SKULL_STND2` thinker state (index 586).
pub const S_SKULL_STND2: c_int = 586;
/// `S_SKULL_RUN1` thinker state (index 587).
pub const S_SKULL_RUN1: c_int = 587;
/// `S_SKULL_RUN2` thinker state (index 588).
pub const S_SKULL_RUN2: c_int = 588;
/// `S_SKULL_ATK1` thinker state (index 589).
pub const S_SKULL_ATK1: c_int = 589;
/// `S_SKULL_ATK2` thinker state (index 590).
pub const S_SKULL_ATK2: c_int = 590;
/// `S_SKULL_ATK3` thinker state (index 591).
pub const S_SKULL_ATK3: c_int = 591;
/// `S_SKULL_ATK4` thinker state (index 592).
pub const S_SKULL_ATK4: c_int = 592;
/// `S_SKULL_PAIN` thinker state (index 593).
pub const S_SKULL_PAIN: c_int = 593;
/// `S_SKULL_PAIN2` thinker state (index 594).
pub const S_SKULL_PAIN2: c_int = 594;
/// `S_SKULL_DIE1` thinker state (index 595).
pub const S_SKULL_DIE1: c_int = 595;
/// `S_SKULL_DIE2` thinker state (index 596).
pub const S_SKULL_DIE2: c_int = 596;
/// `S_SKULL_DIE3` thinker state (index 597).
pub const S_SKULL_DIE3: c_int = 597;
/// `S_SKULL_DIE4` thinker state (index 598).
pub const S_SKULL_DIE4: c_int = 598;
/// `S_SKULL_DIE5` thinker state (index 599).
pub const S_SKULL_DIE5: c_int = 599;
/// `S_SKULL_DIE6` thinker state (index 600).
pub const S_SKULL_DIE6: c_int = 600;
/// `S_SPID_STND` thinker state (index 601).
pub const S_SPID_STND: c_int = 601;
/// `S_SPID_STND2` thinker state (index 602).
pub const S_SPID_STND2: c_int = 602;
/// `S_SPID_RUN1` thinker state (index 603).
pub const S_SPID_RUN1: c_int = 603;
/// `S_SPID_RUN2` thinker state (index 604).
pub const S_SPID_RUN2: c_int = 604;
/// `S_SPID_RUN3` thinker state (index 605).
pub const S_SPID_RUN3: c_int = 605;
/// `S_SPID_RUN4` thinker state (index 606).
pub const S_SPID_RUN4: c_int = 606;
/// `S_SPID_RUN5` thinker state (index 607).
pub const S_SPID_RUN5: c_int = 607;
/// `S_SPID_RUN6` thinker state (index 608).
pub const S_SPID_RUN6: c_int = 608;
/// `S_SPID_RUN7` thinker state (index 609).
pub const S_SPID_RUN7: c_int = 609;
/// `S_SPID_RUN8` thinker state (index 610).
pub const S_SPID_RUN8: c_int = 610;
/// `S_SPID_RUN9` thinker state (index 611).
pub const S_SPID_RUN9: c_int = 611;
/// `S_SPID_RUN10` thinker state (index 612).
pub const S_SPID_RUN10: c_int = 612;
/// `S_SPID_RUN11` thinker state (index 613).
pub const S_SPID_RUN11: c_int = 613;
/// `S_SPID_RUN12` thinker state (index 614).
pub const S_SPID_RUN12: c_int = 614;
/// `S_SPID_ATK1` thinker state (index 615).
pub const S_SPID_ATK1: c_int = 615;
/// `S_SPID_ATK2` thinker state (index 616).
pub const S_SPID_ATK2: c_int = 616;
/// `S_SPID_ATK3` thinker state (index 617).
pub const S_SPID_ATK3: c_int = 617;
/// `S_SPID_ATK4` thinker state (index 618).
pub const S_SPID_ATK4: c_int = 618;
/// `S_SPID_PAIN` thinker state (index 619).
pub const S_SPID_PAIN: c_int = 619;
/// `S_SPID_PAIN2` thinker state (index 620).
pub const S_SPID_PAIN2: c_int = 620;
/// `S_SPID_DIE1` thinker state (index 621).
pub const S_SPID_DIE1: c_int = 621;
/// `S_SPID_DIE2` thinker state (index 622).
pub const S_SPID_DIE2: c_int = 622;
/// `S_SPID_DIE3` thinker state (index 623).
pub const S_SPID_DIE3: c_int = 623;
/// `S_SPID_DIE4` thinker state (index 624).
pub const S_SPID_DIE4: c_int = 624;
/// `S_SPID_DIE5` thinker state (index 625).
pub const S_SPID_DIE5: c_int = 625;
/// `S_SPID_DIE6` thinker state (index 626).
pub const S_SPID_DIE6: c_int = 626;
/// `S_SPID_DIE7` thinker state (index 627).
pub const S_SPID_DIE7: c_int = 627;
/// `S_SPID_DIE8` thinker state (index 628).
pub const S_SPID_DIE8: c_int = 628;
/// `S_SPID_DIE9` thinker state (index 629).
pub const S_SPID_DIE9: c_int = 629;
/// `S_SPID_DIE10` thinker state (index 630).
pub const S_SPID_DIE10: c_int = 630;
/// `S_SPID_DIE11` thinker state (index 631).
pub const S_SPID_DIE11: c_int = 631;
/// `S_BSPI_STND` thinker state (index 632).
pub const S_BSPI_STND: c_int = 632;
/// `S_BSPI_STND2` thinker state (index 633).
pub const S_BSPI_STND2: c_int = 633;
/// `S_BSPI_SIGHT` thinker state (index 634).
pub const S_BSPI_SIGHT: c_int = 634;
/// `S_BSPI_RUN1` thinker state (index 635).
pub const S_BSPI_RUN1: c_int = 635;
/// `S_BSPI_RUN2` thinker state (index 636).
pub const S_BSPI_RUN2: c_int = 636;
/// `S_BSPI_RUN3` thinker state (index 637).
pub const S_BSPI_RUN3: c_int = 637;
/// `S_BSPI_RUN4` thinker state (index 638).
pub const S_BSPI_RUN4: c_int = 638;
/// `S_BSPI_RUN5` thinker state (index 639).
pub const S_BSPI_RUN5: c_int = 639;
/// `S_BSPI_RUN6` thinker state (index 640).
pub const S_BSPI_RUN6: c_int = 640;
/// `S_BSPI_RUN7` thinker state (index 641).
pub const S_BSPI_RUN7: c_int = 641;
/// `S_BSPI_RUN8` thinker state (index 642).
pub const S_BSPI_RUN8: c_int = 642;
/// `S_BSPI_RUN9` thinker state (index 643).
pub const S_BSPI_RUN9: c_int = 643;
/// `S_BSPI_RUN10` thinker state (index 644).
pub const S_BSPI_RUN10: c_int = 644;
/// `S_BSPI_RUN11` thinker state (index 645).
pub const S_BSPI_RUN11: c_int = 645;
/// `S_BSPI_RUN12` thinker state (index 646).
pub const S_BSPI_RUN12: c_int = 646;
/// `S_BSPI_ATK1` thinker state (index 647).
pub const S_BSPI_ATK1: c_int = 647;
/// `S_BSPI_ATK2` thinker state (index 648).
pub const S_BSPI_ATK2: c_int = 648;
/// `S_BSPI_ATK3` thinker state (index 649).
pub const S_BSPI_ATK3: c_int = 649;
/// `S_BSPI_ATK4` thinker state (index 650).
pub const S_BSPI_ATK4: c_int = 650;
/// `S_BSPI_PAIN` thinker state (index 651).
pub const S_BSPI_PAIN: c_int = 651;
/// `S_BSPI_PAIN2` thinker state (index 652).
pub const S_BSPI_PAIN2: c_int = 652;
/// `S_BSPI_DIE1` thinker state (index 653).
pub const S_BSPI_DIE1: c_int = 653;
/// `S_BSPI_DIE2` thinker state (index 654).
pub const S_BSPI_DIE2: c_int = 654;
/// `S_BSPI_DIE3` thinker state (index 655).
pub const S_BSPI_DIE3: c_int = 655;
/// `S_BSPI_DIE4` thinker state (index 656).
pub const S_BSPI_DIE4: c_int = 656;
/// `S_BSPI_DIE5` thinker state (index 657).
pub const S_BSPI_DIE5: c_int = 657;
/// `S_BSPI_DIE6` thinker state (index 658).
pub const S_BSPI_DIE6: c_int = 658;
/// `S_BSPI_DIE7` thinker state (index 659).
pub const S_BSPI_DIE7: c_int = 659;
/// `S_BSPI_RAISE1` thinker state (index 660).
pub const S_BSPI_RAISE1: c_int = 660;
/// `S_BSPI_RAISE2` thinker state (index 661).
pub const S_BSPI_RAISE2: c_int = 661;
/// `S_BSPI_RAISE3` thinker state (index 662).
pub const S_BSPI_RAISE3: c_int = 662;
/// `S_BSPI_RAISE4` thinker state (index 663).
pub const S_BSPI_RAISE4: c_int = 663;
/// `S_BSPI_RAISE5` thinker state (index 664).
pub const S_BSPI_RAISE5: c_int = 664;
/// `S_BSPI_RAISE6` thinker state (index 665).
pub const S_BSPI_RAISE6: c_int = 665;
/// `S_BSPI_RAISE7` thinker state (index 666).
pub const S_BSPI_RAISE7: c_int = 666;
/// `S_ARACH_PLAZ` thinker state (index 667).
pub const S_ARACH_PLAZ: c_int = 667;
/// `S_ARACH_PLAZ2` thinker state (index 668).
pub const S_ARACH_PLAZ2: c_int = 668;
/// `S_ARACH_PLEX` thinker state (index 669).
pub const S_ARACH_PLEX: c_int = 669;
/// `S_ARACH_PLEX2` thinker state (index 670).
pub const S_ARACH_PLEX2: c_int = 670;
/// `S_ARACH_PLEX3` thinker state (index 671).
pub const S_ARACH_PLEX3: c_int = 671;
/// `S_ARACH_PLEX4` thinker state (index 672).
pub const S_ARACH_PLEX4: c_int = 672;
/// `S_ARACH_PLEX5` thinker state (index 673).
pub const S_ARACH_PLEX5: c_int = 673;
/// `S_CYBER_STND` thinker state (index 674).
pub const S_CYBER_STND: c_int = 674;
/// `S_CYBER_STND2` thinker state (index 675).
pub const S_CYBER_STND2: c_int = 675;
/// `S_CYBER_RUN1` thinker state (index 676).
pub const S_CYBER_RUN1: c_int = 676;
/// `S_CYBER_RUN2` thinker state (index 677).
pub const S_CYBER_RUN2: c_int = 677;
/// `S_CYBER_RUN3` thinker state (index 678).
pub const S_CYBER_RUN3: c_int = 678;
/// `S_CYBER_RUN4` thinker state (index 679).
pub const S_CYBER_RUN4: c_int = 679;
/// `S_CYBER_RUN5` thinker state (index 680).
pub const S_CYBER_RUN5: c_int = 680;
/// `S_CYBER_RUN6` thinker state (index 681).
pub const S_CYBER_RUN6: c_int = 681;
/// `S_CYBER_RUN7` thinker state (index 682).
pub const S_CYBER_RUN7: c_int = 682;
/// `S_CYBER_RUN8` thinker state (index 683).
pub const S_CYBER_RUN8: c_int = 683;
/// `S_CYBER_ATK1` thinker state (index 684).
pub const S_CYBER_ATK1: c_int = 684;
/// `S_CYBER_ATK2` thinker state (index 685).
pub const S_CYBER_ATK2: c_int = 685;
/// `S_CYBER_ATK3` thinker state (index 686).
pub const S_CYBER_ATK3: c_int = 686;
/// `S_CYBER_ATK4` thinker state (index 687).
pub const S_CYBER_ATK4: c_int = 687;
/// `S_CYBER_ATK5` thinker state (index 688).
pub const S_CYBER_ATK5: c_int = 688;
/// `S_CYBER_ATK6` thinker state (index 689).
pub const S_CYBER_ATK6: c_int = 689;
/// `S_CYBER_PAIN` thinker state (index 690).
pub const S_CYBER_PAIN: c_int = 690;
/// `S_CYBER_DIE1` thinker state (index 691).
pub const S_CYBER_DIE1: c_int = 691;
/// `S_CYBER_DIE2` thinker state (index 692).
pub const S_CYBER_DIE2: c_int = 692;
/// `S_CYBER_DIE3` thinker state (index 693).
pub const S_CYBER_DIE3: c_int = 693;
/// `S_CYBER_DIE4` thinker state (index 694).
pub const S_CYBER_DIE4: c_int = 694;
/// `S_CYBER_DIE5` thinker state (index 695).
pub const S_CYBER_DIE5: c_int = 695;
/// `S_CYBER_DIE6` thinker state (index 696).
pub const S_CYBER_DIE6: c_int = 696;
/// `S_CYBER_DIE7` thinker state (index 697).
pub const S_CYBER_DIE7: c_int = 697;
/// `S_CYBER_DIE8` thinker state (index 698).
pub const S_CYBER_DIE8: c_int = 698;
/// `S_CYBER_DIE9` thinker state (index 699).
pub const S_CYBER_DIE9: c_int = 699;
/// `S_CYBER_DIE10` thinker state (index 700).
pub const S_CYBER_DIE10: c_int = 700;
/// `S_PAIN_STND` thinker state (index 701).
pub const S_PAIN_STND: c_int = 701;
/// `S_PAIN_RUN1` thinker state (index 702).
pub const S_PAIN_RUN1: c_int = 702;
/// `S_PAIN_RUN2` thinker state (index 703).
pub const S_PAIN_RUN2: c_int = 703;
/// `S_PAIN_RUN3` thinker state (index 704).
pub const S_PAIN_RUN3: c_int = 704;
/// `S_PAIN_RUN4` thinker state (index 705).
pub const S_PAIN_RUN4: c_int = 705;
/// `S_PAIN_RUN5` thinker state (index 706).
pub const S_PAIN_RUN5: c_int = 706;
/// `S_PAIN_RUN6` thinker state (index 707).
pub const S_PAIN_RUN6: c_int = 707;
/// `S_PAIN_ATK1` thinker state (index 708).
pub const S_PAIN_ATK1: c_int = 708;
/// `S_PAIN_ATK2` thinker state (index 709).
pub const S_PAIN_ATK2: c_int = 709;
/// `S_PAIN_ATK3` thinker state (index 710).
pub const S_PAIN_ATK3: c_int = 710;
/// `S_PAIN_ATK4` thinker state (index 711).
pub const S_PAIN_ATK4: c_int = 711;
/// `S_PAIN_PAIN` thinker state (index 712).
pub const S_PAIN_PAIN: c_int = 712;
/// `S_PAIN_PAIN2` thinker state (index 713).
pub const S_PAIN_PAIN2: c_int = 713;
/// `S_PAIN_DIE1` thinker state (index 714).
pub const S_PAIN_DIE1: c_int = 714;
/// `S_PAIN_DIE2` thinker state (index 715).
pub const S_PAIN_DIE2: c_int = 715;
/// `S_PAIN_DIE3` thinker state (index 716).
pub const S_PAIN_DIE3: c_int = 716;
/// `S_PAIN_DIE4` thinker state (index 717).
pub const S_PAIN_DIE4: c_int = 717;
/// `S_PAIN_DIE5` thinker state (index 718).
pub const S_PAIN_DIE5: c_int = 718;
/// `S_PAIN_DIE6` thinker state (index 719).
pub const S_PAIN_DIE6: c_int = 719;
/// `S_PAIN_RAISE1` thinker state (index 720).
pub const S_PAIN_RAISE1: c_int = 720;
/// `S_PAIN_RAISE2` thinker state (index 721).
pub const S_PAIN_RAISE2: c_int = 721;
/// `S_PAIN_RAISE3` thinker state (index 722).
pub const S_PAIN_RAISE3: c_int = 722;
/// `S_PAIN_RAISE4` thinker state (index 723).
pub const S_PAIN_RAISE4: c_int = 723;
/// `S_PAIN_RAISE5` thinker state (index 724).
pub const S_PAIN_RAISE5: c_int = 724;
/// `S_PAIN_RAISE6` thinker state (index 725).
pub const S_PAIN_RAISE6: c_int = 725;
/// `S_SSWV_STND` thinker state (index 726).
pub const S_SSWV_STND: c_int = 726;
/// `S_SSWV_STND2` thinker state (index 727).
pub const S_SSWV_STND2: c_int = 727;
/// `S_SSWV_RUN1` thinker state (index 728).
pub const S_SSWV_RUN1: c_int = 728;
/// `S_SSWV_RUN2` thinker state (index 729).
pub const S_SSWV_RUN2: c_int = 729;
/// `S_SSWV_RUN3` thinker state (index 730).
pub const S_SSWV_RUN3: c_int = 730;
/// `S_SSWV_RUN4` thinker state (index 731).
pub const S_SSWV_RUN4: c_int = 731;
/// `S_SSWV_RUN5` thinker state (index 732).
pub const S_SSWV_RUN5: c_int = 732;
/// `S_SSWV_RUN6` thinker state (index 733).
pub const S_SSWV_RUN6: c_int = 733;
/// `S_SSWV_RUN7` thinker state (index 734).
pub const S_SSWV_RUN7: c_int = 734;
/// `S_SSWV_RUN8` thinker state (index 735).
pub const S_SSWV_RUN8: c_int = 735;
/// `S_SSWV_ATK1` thinker state (index 736).
pub const S_SSWV_ATK1: c_int = 736;
/// `S_SSWV_ATK2` thinker state (index 737).
pub const S_SSWV_ATK2: c_int = 737;
/// `S_SSWV_ATK3` thinker state (index 738).
pub const S_SSWV_ATK3: c_int = 738;
/// `S_SSWV_ATK4` thinker state (index 739).
pub const S_SSWV_ATK4: c_int = 739;
/// `S_SSWV_ATK5` thinker state (index 740).
pub const S_SSWV_ATK5: c_int = 740;
/// `S_SSWV_ATK6` thinker state (index 741).
pub const S_SSWV_ATK6: c_int = 741;
/// `S_SSWV_PAIN` thinker state (index 742).
pub const S_SSWV_PAIN: c_int = 742;
/// `S_SSWV_PAIN2` thinker state (index 743).
pub const S_SSWV_PAIN2: c_int = 743;
/// `S_SSWV_DIE1` thinker state (index 744).
pub const S_SSWV_DIE1: c_int = 744;
/// `S_SSWV_DIE2` thinker state (index 745).
pub const S_SSWV_DIE2: c_int = 745;
/// `S_SSWV_DIE3` thinker state (index 746).
pub const S_SSWV_DIE3: c_int = 746;
/// `S_SSWV_DIE4` thinker state (index 747).
pub const S_SSWV_DIE4: c_int = 747;
/// `S_SSWV_DIE5` thinker state (index 748).
pub const S_SSWV_DIE5: c_int = 748;
/// `S_SSWV_XDIE1` thinker state (index 749).
pub const S_SSWV_XDIE1: c_int = 749;
/// `S_SSWV_XDIE2` thinker state (index 750).
pub const S_SSWV_XDIE2: c_int = 750;
/// `S_SSWV_XDIE3` thinker state (index 751).
pub const S_SSWV_XDIE3: c_int = 751;
/// `S_SSWV_XDIE4` thinker state (index 752).
pub const S_SSWV_XDIE4: c_int = 752;
/// `S_SSWV_XDIE5` thinker state (index 753).
pub const S_SSWV_XDIE5: c_int = 753;
/// `S_SSWV_XDIE6` thinker state (index 754).
pub const S_SSWV_XDIE6: c_int = 754;
/// `S_SSWV_XDIE7` thinker state (index 755).
pub const S_SSWV_XDIE7: c_int = 755;
/// `S_SSWV_XDIE8` thinker state (index 756).
pub const S_SSWV_XDIE8: c_int = 756;
/// `S_SSWV_XDIE9` thinker state (index 757).
pub const S_SSWV_XDIE9: c_int = 757;
/// `S_SSWV_RAISE1` thinker state (index 758).
pub const S_SSWV_RAISE1: c_int = 758;
/// `S_SSWV_RAISE2` thinker state (index 759).
pub const S_SSWV_RAISE2: c_int = 759;
/// `S_SSWV_RAISE3` thinker state (index 760).
pub const S_SSWV_RAISE3: c_int = 760;
/// `S_SSWV_RAISE4` thinker state (index 761).
pub const S_SSWV_RAISE4: c_int = 761;
/// `S_SSWV_RAISE5` thinker state (index 762).
pub const S_SSWV_RAISE5: c_int = 762;
/// `S_KEENSTND` thinker state (index 763).
pub const S_KEENSTND: c_int = 763;
/// `S_COMMKEEN` thinker state (index 764).
pub const S_COMMKEEN: c_int = 764;
/// `S_COMMKEEN2` thinker state (index 765).
pub const S_COMMKEEN2: c_int = 765;
/// `S_COMMKEEN3` thinker state (index 766).
pub const S_COMMKEEN3: c_int = 766;
/// `S_COMMKEEN4` thinker state (index 767).
pub const S_COMMKEEN4: c_int = 767;
/// `S_COMMKEEN5` thinker state (index 768).
pub const S_COMMKEEN5: c_int = 768;
/// `S_COMMKEEN6` thinker state (index 769).
pub const S_COMMKEEN6: c_int = 769;
/// `S_COMMKEEN7` thinker state (index 770).
pub const S_COMMKEEN7: c_int = 770;
/// `S_COMMKEEN8` thinker state (index 771).
pub const S_COMMKEEN8: c_int = 771;
/// `S_COMMKEEN9` thinker state (index 772).
pub const S_COMMKEEN9: c_int = 772;
/// `S_COMMKEEN10` thinker state (index 773).
pub const S_COMMKEEN10: c_int = 773;
/// `S_COMMKEEN11` thinker state (index 774).
pub const S_COMMKEEN11: c_int = 774;
/// `S_COMMKEEN12` thinker state (index 775).
pub const S_COMMKEEN12: c_int = 775;
/// `S_KEENPAIN` thinker state (index 776).
pub const S_KEENPAIN: c_int = 776;
/// `S_KEENPAIN2` thinker state (index 777).
pub const S_KEENPAIN2: c_int = 777;
/// `S_BRAIN` thinker state (index 778).
pub const S_BRAIN: c_int = 778;
/// `S_BRAIN_PAIN` thinker state (index 779).
pub const S_BRAIN_PAIN: c_int = 779;
/// `S_BRAIN_DIE1` thinker state (index 780).
pub const S_BRAIN_DIE1: c_int = 780;
/// `S_BRAIN_DIE2` thinker state (index 781).
pub const S_BRAIN_DIE2: c_int = 781;
/// `S_BRAIN_DIE3` thinker state (index 782).
pub const S_BRAIN_DIE3: c_int = 782;
/// `S_BRAIN_DIE4` thinker state (index 783).
pub const S_BRAIN_DIE4: c_int = 783;
/// `S_BRAINEYE` thinker state (index 784).
pub const S_BRAINEYE: c_int = 784;
/// `S_BRAINEYESEE` thinker state (index 785).
pub const S_BRAINEYESEE: c_int = 785;
/// `S_BRAINEYE1` thinker state (index 786).
pub const S_BRAINEYE1: c_int = 786;
/// `S_SPAWN1` thinker state (index 787).
pub const S_SPAWN1: c_int = 787;
/// `S_SPAWN2` thinker state (index 788).
pub const S_SPAWN2: c_int = 788;
/// `S_SPAWN3` thinker state (index 789).
pub const S_SPAWN3: c_int = 789;
/// `S_SPAWN4` thinker state (index 790).
pub const S_SPAWN4: c_int = 790;
/// `S_SPAWNFIRE1` thinker state (index 791).
pub const S_SPAWNFIRE1: c_int = 791;
/// `S_SPAWNFIRE2` thinker state (index 792).
pub const S_SPAWNFIRE2: c_int = 792;
/// `S_SPAWNFIRE3` thinker state (index 793).
pub const S_SPAWNFIRE3: c_int = 793;
/// `S_SPAWNFIRE4` thinker state (index 794).
pub const S_SPAWNFIRE4: c_int = 794;
/// `S_SPAWNFIRE5` thinker state (index 795).
pub const S_SPAWNFIRE5: c_int = 795;
/// `S_SPAWNFIRE6` thinker state (index 796).
pub const S_SPAWNFIRE6: c_int = 796;
/// `S_SPAWNFIRE7` thinker state (index 797).
pub const S_SPAWNFIRE7: c_int = 797;
/// `S_SPAWNFIRE8` thinker state (index 798).
pub const S_SPAWNFIRE8: c_int = 798;
/// `S_BRAINEXPLODE1` thinker state (index 799).
pub const S_BRAINEXPLODE1: c_int = 799;
/// `S_BRAINEXPLODE2` thinker state (index 800).
pub const S_BRAINEXPLODE2: c_int = 800;
/// `S_BRAINEXPLODE3` thinker state (index 801).
pub const S_BRAINEXPLODE3: c_int = 801;
/// `S_ARM1` thinker state (index 802).
pub const S_ARM1: c_int = 802;
/// `S_ARM1A` thinker state (index 803).
pub const S_ARM1A: c_int = 803;
/// `S_ARM2` thinker state (index 804).
pub const S_ARM2: c_int = 804;
/// `S_ARM2A` thinker state (index 805).
pub const S_ARM2A: c_int = 805;
/// `S_BAR1` thinker state (index 806).
pub const S_BAR1: c_int = 806;
/// `S_BAR2` thinker state (index 807).
pub const S_BAR2: c_int = 807;
/// `S_BEXP` thinker state (index 808).
pub const S_BEXP: c_int = 808;
/// `S_BEXP2` thinker state (index 809).
pub const S_BEXP2: c_int = 809;
/// `S_BEXP3` thinker state (index 810).
pub const S_BEXP3: c_int = 810;
/// `S_BEXP4` thinker state (index 811).
pub const S_BEXP4: c_int = 811;
/// `S_BEXP5` thinker state (index 812).
pub const S_BEXP5: c_int = 812;
/// `S_BBAR1` thinker state (index 813).
pub const S_BBAR1: c_int = 813;
/// `S_BBAR2` thinker state (index 814).
pub const S_BBAR2: c_int = 814;
/// `S_BBAR3` thinker state (index 815).
pub const S_BBAR3: c_int = 815;
/// `S_BON1` thinker state (index 816).
pub const S_BON1: c_int = 816;
/// `S_BON1A` thinker state (index 817).
pub const S_BON1A: c_int = 817;
/// `S_BON1B` thinker state (index 818).
pub const S_BON1B: c_int = 818;
/// `S_BON1C` thinker state (index 819).
pub const S_BON1C: c_int = 819;
/// `S_BON1D` thinker state (index 820).
pub const S_BON1D: c_int = 820;
/// `S_BON1E` thinker state (index 821).
pub const S_BON1E: c_int = 821;
/// `S_BON2` thinker state (index 822).
pub const S_BON2: c_int = 822;
/// `S_BON2A` thinker state (index 823).
pub const S_BON2A: c_int = 823;
/// `S_BON2B` thinker state (index 824).
pub const S_BON2B: c_int = 824;
/// `S_BON2C` thinker state (index 825).
pub const S_BON2C: c_int = 825;
/// `S_BON2D` thinker state (index 826).
pub const S_BON2D: c_int = 826;
/// `S_BON2E` thinker state (index 827).
pub const S_BON2E: c_int = 827;
/// `S_BKEY` thinker state (index 828).
pub const S_BKEY: c_int = 828;
/// `S_BKEY2` thinker state (index 829).
pub const S_BKEY2: c_int = 829;
/// `S_RKEY` thinker state (index 830).
pub const S_RKEY: c_int = 830;
/// `S_RKEY2` thinker state (index 831).
pub const S_RKEY2: c_int = 831;
/// `S_YKEY` thinker state (index 832).
pub const S_YKEY: c_int = 832;
/// `S_YKEY2` thinker state (index 833).
pub const S_YKEY2: c_int = 833;
/// `S_BSKULL` thinker state (index 834).
pub const S_BSKULL: c_int = 834;
/// `S_BSKULL2` thinker state (index 835).
pub const S_BSKULL2: c_int = 835;
/// `S_RSKULL` thinker state (index 836).
pub const S_RSKULL: c_int = 836;
/// `S_RSKULL2` thinker state (index 837).
pub const S_RSKULL2: c_int = 837;
/// `S_YSKULL` thinker state (index 838).
pub const S_YSKULL: c_int = 838;
/// `S_YSKULL2` thinker state (index 839).
pub const S_YSKULL2: c_int = 839;
/// `S_STIM` thinker state (index 840).
pub const S_STIM: c_int = 840;
/// `S_MEDI` thinker state (index 841).
pub const S_MEDI: c_int = 841;
/// `S_SOUL` thinker state (index 842).
pub const S_SOUL: c_int = 842;
/// `S_SOUL2` thinker state (index 843).
pub const S_SOUL2: c_int = 843;
/// `S_SOUL3` thinker state (index 844).
pub const S_SOUL3: c_int = 844;
/// `S_SOUL4` thinker state (index 845).
pub const S_SOUL4: c_int = 845;
/// `S_SOUL5` thinker state (index 846).
pub const S_SOUL5: c_int = 846;
/// `S_SOUL6` thinker state (index 847).
pub const S_SOUL6: c_int = 847;
/// `S_PINV` thinker state (index 848).
pub const S_PINV: c_int = 848;
/// `S_PINV2` thinker state (index 849).
pub const S_PINV2: c_int = 849;
/// `S_PINV3` thinker state (index 850).
pub const S_PINV3: c_int = 850;
/// `S_PINV4` thinker state (index 851).
pub const S_PINV4: c_int = 851;
/// `S_PSTR` thinker state (index 852).
pub const S_PSTR: c_int = 852;
/// `S_PINS` thinker state (index 853).
pub const S_PINS: c_int = 853;
/// `S_PINS2` thinker state (index 854).
pub const S_PINS2: c_int = 854;
/// `S_PINS3` thinker state (index 855).
pub const S_PINS3: c_int = 855;
/// `S_PINS4` thinker state (index 856).
pub const S_PINS4: c_int = 856;
/// `S_MEGA` thinker state (index 857).
pub const S_MEGA: c_int = 857;
/// `S_MEGA2` thinker state (index 858).
pub const S_MEGA2: c_int = 858;
/// `S_MEGA3` thinker state (index 859).
pub const S_MEGA3: c_int = 859;
/// `S_MEGA4` thinker state (index 860).
pub const S_MEGA4: c_int = 860;
/// `S_SUIT` thinker state (index 861).
pub const S_SUIT: c_int = 861;
/// `S_PMAP` thinker state (index 862).
pub const S_PMAP: c_int = 862;
/// `S_PMAP2` thinker state (index 863).
pub const S_PMAP2: c_int = 863;
/// `S_PMAP3` thinker state (index 864).
pub const S_PMAP3: c_int = 864;
/// `S_PMAP4` thinker state (index 865).
pub const S_PMAP4: c_int = 865;
/// `S_PMAP5` thinker state (index 866).
pub const S_PMAP5: c_int = 866;
/// `S_PMAP6` thinker state (index 867).
pub const S_PMAP6: c_int = 867;
/// `S_PVIS` thinker state (index 868).
pub const S_PVIS: c_int = 868;
/// `S_PVIS2` thinker state (index 869).
pub const S_PVIS2: c_int = 869;
/// `S_CLIP` thinker state (index 870).
pub const S_CLIP: c_int = 870;
/// `S_AMMO` thinker state (index 871).
pub const S_AMMO: c_int = 871;
/// `S_ROCK` thinker state (index 872).
pub const S_ROCK: c_int = 872;
/// `S_BROK` thinker state (index 873).
pub const S_BROK: c_int = 873;
/// `S_CELL` thinker state (index 874).
pub const S_CELL: c_int = 874;
/// `S_CELP` thinker state (index 875).
pub const S_CELP: c_int = 875;
/// `S_SHEL` thinker state (index 876).
pub const S_SHEL: c_int = 876;
/// `S_SBOX` thinker state (index 877).
pub const S_SBOX: c_int = 877;
/// `S_BPAK` thinker state (index 878).
pub const S_BPAK: c_int = 878;
/// `S_BFUG` thinker state (index 879).
pub const S_BFUG: c_int = 879;
/// `S_MGUN` thinker state (index 880).
pub const S_MGUN: c_int = 880;
/// `S_CSAW` thinker state (index 881).
pub const S_CSAW: c_int = 881;
/// `S_LAUN` thinker state (index 882).
pub const S_LAUN: c_int = 882;
/// `S_PLAS` thinker state (index 883).
pub const S_PLAS: c_int = 883;
/// `S_SHOT` thinker state (index 884).
pub const S_SHOT: c_int = 884;
/// `S_SHOT2` thinker state (index 885).
pub const S_SHOT2: c_int = 885;
/// `S_COLU` thinker state (index 886).
pub const S_COLU: c_int = 886;
/// `S_STALAG` thinker state (index 887).
pub const S_STALAG: c_int = 887;
/// `S_BLOODYTWITCH` thinker state (index 888).
pub const S_BLOODYTWITCH: c_int = 888;
/// `S_BLOODYTWITCH2` thinker state (index 889).
pub const S_BLOODYTWITCH2: c_int = 889;
/// `S_BLOODYTWITCH3` thinker state (index 890).
pub const S_BLOODYTWITCH3: c_int = 890;
/// `S_BLOODYTWITCH4` thinker state (index 891).
pub const S_BLOODYTWITCH4: c_int = 891;
/// `S_DEADTORSO` thinker state (index 892).
pub const S_DEADTORSO: c_int = 892;
/// `S_DEADBOTTOM` thinker state (index 893).
pub const S_DEADBOTTOM: c_int = 893;
/// `S_HEADSONSTICK` thinker state (index 894).
pub const S_HEADSONSTICK: c_int = 894;
/// `S_GIBS` thinker state (index 895).
pub const S_GIBS: c_int = 895;
/// `S_HEADONASTICK` thinker state (index 896).
pub const S_HEADONASTICK: c_int = 896;
/// `S_HEADCANDLES` thinker state (index 897).
pub const S_HEADCANDLES: c_int = 897;
/// `S_HEADCANDLES2` thinker state (index 898).
pub const S_HEADCANDLES2: c_int = 898;
/// `S_DEADSTICK` thinker state (index 899).
pub const S_DEADSTICK: c_int = 899;
/// `S_LIVESTICK` thinker state (index 900).
pub const S_LIVESTICK: c_int = 900;
/// `S_LIVESTICK2` thinker state (index 901).
pub const S_LIVESTICK2: c_int = 901;
/// `S_MEAT2` thinker state (index 902).
pub const S_MEAT2: c_int = 902;
/// `S_MEAT3` thinker state (index 903).
pub const S_MEAT3: c_int = 903;
/// `S_MEAT4` thinker state (index 904).
pub const S_MEAT4: c_int = 904;
/// `S_MEAT5` thinker state (index 905).
pub const S_MEAT5: c_int = 905;
/// `S_STALAGTITE` thinker state (index 906).
pub const S_STALAGTITE: c_int = 906;
/// `S_TALLGRNCOL` thinker state (index 907).
pub const S_TALLGRNCOL: c_int = 907;
/// `S_SHRTGRNCOL` thinker state (index 908).
pub const S_SHRTGRNCOL: c_int = 908;
/// `S_TALLREDCOL` thinker state (index 909).
pub const S_TALLREDCOL: c_int = 909;
/// `S_SHRTREDCOL` thinker state (index 910).
pub const S_SHRTREDCOL: c_int = 910;
/// `S_CANDLESTIK` thinker state (index 911).
pub const S_CANDLESTIK: c_int = 911;
/// `S_CANDELABRA` thinker state (index 912).
pub const S_CANDELABRA: c_int = 912;
/// `S_SKULLCOL` thinker state (index 913).
pub const S_SKULLCOL: c_int = 913;
/// `S_TORCHTREE` thinker state (index 914).
pub const S_TORCHTREE: c_int = 914;
/// `S_BIGTREE` thinker state (index 915).
pub const S_BIGTREE: c_int = 915;
/// `S_TECHPILLAR` thinker state (index 916).
pub const S_TECHPILLAR: c_int = 916;
/// `S_EVILEYE` thinker state (index 917).
pub const S_EVILEYE: c_int = 917;
/// `S_EVILEYE2` thinker state (index 918).
pub const S_EVILEYE2: c_int = 918;
/// `S_EVILEYE3` thinker state (index 919).
pub const S_EVILEYE3: c_int = 919;
/// `S_EVILEYE4` thinker state (index 920).
pub const S_EVILEYE4: c_int = 920;
/// `S_FLOATSKULL` thinker state (index 921).
pub const S_FLOATSKULL: c_int = 921;
/// `S_FLOATSKULL2` thinker state (index 922).
pub const S_FLOATSKULL2: c_int = 922;
/// `S_FLOATSKULL3` thinker state (index 923).
pub const S_FLOATSKULL3: c_int = 923;
/// `S_HEARTCOL` thinker state (index 924).
pub const S_HEARTCOL: c_int = 924;
/// `S_HEARTCOL2` thinker state (index 925).
pub const S_HEARTCOL2: c_int = 925;
/// `S_BLUETORCH` thinker state (index 926).
pub const S_BLUETORCH: c_int = 926;
/// `S_BLUETORCH2` thinker state (index 927).
pub const S_BLUETORCH2: c_int = 927;
/// `S_BLUETORCH3` thinker state (index 928).
pub const S_BLUETORCH3: c_int = 928;
/// `S_BLUETORCH4` thinker state (index 929).
pub const S_BLUETORCH4: c_int = 929;
/// `S_GREENTORCH` thinker state (index 930).
pub const S_GREENTORCH: c_int = 930;
/// `S_GREENTORCH2` thinker state (index 931).
pub const S_GREENTORCH2: c_int = 931;
/// `S_GREENTORCH3` thinker state (index 932).
pub const S_GREENTORCH3: c_int = 932;
/// `S_GREENTORCH4` thinker state (index 933).
pub const S_GREENTORCH4: c_int = 933;
/// `S_REDTORCH` thinker state (index 934).
pub const S_REDTORCH: c_int = 934;
/// `S_REDTORCH2` thinker state (index 935).
pub const S_REDTORCH2: c_int = 935;
/// `S_REDTORCH3` thinker state (index 936).
pub const S_REDTORCH3: c_int = 936;
/// `S_REDTORCH4` thinker state (index 937).
pub const S_REDTORCH4: c_int = 937;
/// `S_BTORCHSHRT` thinker state (index 938).
pub const S_BTORCHSHRT: c_int = 938;
/// `S_BTORCHSHRT2` thinker state (index 939).
pub const S_BTORCHSHRT2: c_int = 939;
/// `S_BTORCHSHRT3` thinker state (index 940).
pub const S_BTORCHSHRT3: c_int = 940;
/// `S_BTORCHSHRT4` thinker state (index 941).
pub const S_BTORCHSHRT4: c_int = 941;
/// `S_GTORCHSHRT` thinker state (index 942).
pub const S_GTORCHSHRT: c_int = 942;
/// `S_GTORCHSHRT2` thinker state (index 943).
pub const S_GTORCHSHRT2: c_int = 943;
/// `S_GTORCHSHRT3` thinker state (index 944).
pub const S_GTORCHSHRT3: c_int = 944;
/// `S_GTORCHSHRT4` thinker state (index 945).
pub const S_GTORCHSHRT4: c_int = 945;
/// `S_RTORCHSHRT` thinker state (index 946).
pub const S_RTORCHSHRT: c_int = 946;
/// `S_RTORCHSHRT2` thinker state (index 947).
pub const S_RTORCHSHRT2: c_int = 947;
/// `S_RTORCHSHRT3` thinker state (index 948).
pub const S_RTORCHSHRT3: c_int = 948;
/// `S_RTORCHSHRT4` thinker state (index 949).
pub const S_RTORCHSHRT4: c_int = 949;
/// `S_HANGNOGUTS` thinker state (index 950).
pub const S_HANGNOGUTS: c_int = 950;
/// `S_HANGBNOBRAIN` thinker state (index 951).
pub const S_HANGBNOBRAIN: c_int = 951;
/// `S_HANGTLOOKDN` thinker state (index 952).
pub const S_HANGTLOOKDN: c_int = 952;
/// `S_HANGTSKULL` thinker state (index 953).
pub const S_HANGTSKULL: c_int = 953;
/// `S_HANGTLOOKUP` thinker state (index 954).
pub const S_HANGTLOOKUP: c_int = 954;
/// `S_HANGTNOBRAIN` thinker state (index 955).
pub const S_HANGTNOBRAIN: c_int = 955;
/// `S_COLONGIBS` thinker state (index 956).
pub const S_COLONGIBS: c_int = 956;
/// `S_SMALLPOOL` thinker state (index 957).
pub const S_SMALLPOOL: c_int = 957;
/// `S_BRAINSTEM` thinker state (index 958).
pub const S_BRAINSTEM: c_int = 958;
/// `S_TECHLAMP` thinker state (index 959).
pub const S_TECHLAMP: c_int = 959;
/// `S_TECHLAMP2` thinker state (index 960).
pub const S_TECHLAMP2: c_int = 960;
/// `S_TECHLAMP3` thinker state (index 961).
pub const S_TECHLAMP3: c_int = 961;
/// `S_TECHLAMP4` thinker state (index 962).
pub const S_TECHLAMP4: c_int = 962;
/// `S_TECH2LAMP` thinker state (index 963).
pub const S_TECH2LAMP: c_int = 963;
/// `S_TECH2LAMP2` thinker state (index 964).
pub const S_TECH2LAMP2: c_int = 964;
/// `S_TECH2LAMP3` thinker state (index 965).
pub const S_TECH2LAMP3: c_int = 965;
/// `S_TECH2LAMP4` thinker state (index 966).
pub const S_TECH2LAMP4: c_int = 966;
